UPDATE agent-screen
* added hive-functions.sh library
* removed library functions
* increased 'agent-screen log' size from 200 to 300 lines
* fixed log output
* improved start/stop functions

diff --git a/hive/bin/agent-screen b/hive/bin/agent-screen
--- a/hive/bin/agent-screen
+++ b/hive/bin/agent-screen
@@ -9,9 +9,10 @@
 
 
 readonly script_mission='Client for ASICs: agent-screen helper'
-readonly script_version='1.0.10'
+readonly script_version='1.0.11'
 readonly script_basename="$( basename "$0" )"
-readonly DEBUG=0
+readonly script_DEBUG=0
+source /hive/bin/hive-functions.sh || { echo 'ERROR: /hive/bin/hive-functions.sh not found'; exit 1; }
 
 
 #
@@ -26,10 +27,6 @@ set -o nounset
 
 # functions
 
-function errcho {
-	# uniform error logging to stderr
-	echo -e "${script_basename}: Error in $0:${FUNCNAME[1]}(): $*"
-} 1>&2
 
 # functions: screen
 
@@ -41,7 +38,7 @@ function is_screen_session_exist {
 	local -r session_name="${1-}"
 
 	# code
-	if (( DEBUG )); then
+	if (( script_DEBUG )); then
 		screen -S "$session_name" -X select .
 	else
 		screen -S "$session_name" -X select . > /dev/null
@@ -62,7 +59,7 @@ function screen_attach_to_session {
 		#
 		# -T term       Use term as $TERM for windows, rather than "screen".
 		#
-		if (( DEBUG )); then
+		if (( script_DEBUG )); then
 			TERM='vt102' screen -x -S "$session_name"
 		else
 			TERM='vt102' screen -x -S "$session_name" > /dev/null
@@ -83,7 +80,7 @@ function screen_start_session {
 	# consts
 	local -r session_name="$cmd"
 	local -r -i retries_limit=100
-	local -r -i scrollback_buffer_lines=200
+	local -r -i scrollback_buffer_lines=300
 
 	# vars
 	local -i retries_counter
@@ -97,17 +94,17 @@ function screen_start_session {
 
 	retries_counter=1
 	until is_screen_session_exist "$session_name"; do
-		if (( retries_counter > 1 )); then
-			{ sleep 0.5 || usleep 500000 || sleep 1; } 2> /dev/null # only integer sleep on BusyBox
-			screen -wipe # > /dev/null # let's debug
-		#else
-			# skip 'sleep' at the first iteration
-		fi
-
-		if (( DEBUG )); then
+		if (( script_DEBUG )); then
 			screen -dm -S "$session_name" -h "$scrollback_buffer_lines" "$cmd" $args
 		else
 			screen -dm -S "$session_name" -h "$scrollback_buffer_lines" "$cmd" $args > /dev/null
+		fi
+
+		if (( retries_counter > 1 )); then
+			snore 1 # sometimes gnu screen is slow
+			screen -wipe # > /dev/null # let's debug
+		#else
+			# skip 'sleep' at the first iteration
 		fi
 
 		(( retries_counter == 2 )) && printf '\n'
@@ -155,16 +152,16 @@ function screen_stop_session {
 	# code
 	retries_counter=1
 	while is_screen_session_exist "$session_name"; do
-		if (( retries_counter > 1 )); then
-			{ sleep 0.5 || usleep 500000 || sleep 1; } 2> /dev/null # only integer sleep on BusyBox
-		#else
-			# skip 'sleep' at the first iteration
-		fi
-
-		if (( DEBUG )); then
+		if (( script_DEBUG )); then
 			screen -S "$session_name" -X quit
 		else
 			screen -S "$session_name" -X quit > /dev/null
+		fi
+
+		if (( retries_counter > 1 )); then
+			snore 1 # sometimes gnu screen is slow
+		#else
+			# skip sleep at the first iteration
 		fi
 
 		(( retries_counter == 2 )) && printf '\n'
@@ -175,8 +172,8 @@ function screen_stop_session {
 			else
 				printf 'Waiting for %s screen session to stop, attempt #%d... \n' "$session_name" "$retries_counter"
 			fi
-			rm -rf /var/run/screens/*."$session_name"
-			screen -wipe
+			#rm -rf /var/run/screens/*."$session_name"
+			screen -wipe # > /dev/null # let's debug
 		fi
 
 		if (( retries_counter >= retries_limit )); then
@@ -235,8 +232,6 @@ function agent_restart {
 # global consts
 
 declare -r own_log="/tmp/${script_basename}.log"
-declare -r -i exitcode_OK=0
-declare -r -i exitcode_ERROR_IN_ARGUMENTS=128
 declare -r -i exitcode_ERROR_CMD_NOT_FOUND=100
 declare -r -i exitcode_ERROR_SOMETHING_BAD_HAPPEN=1
 declare -r -i script_exitcode_OK_RUNNING=0
@@ -245,9 +240,7 @@ declare -r -i script_exitcode_OK_NOT_RUNNING_STARTED=1
 
 # global vars
 
-# exitcode=0 - has been running
-# exitcode=1 - has not been running, starting
-declare -i script_exitcode
+declare -i script_exitcode	# 0 = has been running, 1 = has not been running, starting
 
 
 # global exports
@@ -255,6 +248,7 @@ declare -i script_exitcode
 [[ ! "$PATH" =~ (^|:)/hive/bin:/hive/sbin(:|$) ]] && export PATH="$PATH:/hive/bin:/hive/sbin"
 [[ ! "$LD_LIBRARY_PATH" =~ (^|:)/hive/lib(:|$) ]] && export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/hive/lib" # save $LD_LIBRARY_PATH:/hive/share/S9/lib for hiveon
 #export LD_LIBRARY_PATH=/hive/lib
+
 
 # traps
 
@@ -273,10 +267,13 @@ case "${1-}" in
 
 	'log')
 		if touch "$own_log" 2> /dev/null; then
-			screen -S agent -X -p0 hardcopy -h "$own_log"
+			screen -S agent -p 0 -X hardcopy -h "$own_log"
 			if [[ -f "$own_log" ]]; then
-				{ grep -v -m 1 '^$' && cat; } < "$own_log" # remove blank lines from beginning, https://stackoverflow.com/a/19775127
+				awk 'NF {f=1} f' "$own_log" # https://stackoverflow.com/a/19767713
 				rm "$own_log"
+			else
+				errcho "screen didn't produce no log"
+				script_exitcode=1
 			fi
 			script_exitcode=0
 		else
@@ -285,9 +282,14 @@ case "${1-}" in
 		fi
 	;;
 
-	'attach' | *)
+	'attach' | '')
 		agent_start
 		screen_attach_to_session 'agent'
+	;;
+
+	*)
+		errcho "Unknown argument '$this_argument'"
+		script_exitcode=1
 	;;
 esac
 
