UPDATE agent
* added dead pool detection and logging
* added a brand new status 'deadpool'
* added sanitizing of server answer to display

diff --git a/hive/bin/agent b/hive/bin/agent
--- a/hive/bin/agent
+++ b/hive/bin/agent
@@ -9,7 +9,7 @@
 
 
 readonly script_mission='Client for ASICs: The Agent'
-readonly script_version='0.3.4'
+readonly script_version='0.4.0'
 readonly script_basename="$( basename "$0" )"
 #
 readonly script_DEBUG="${script_DEBUG:-0}" # use value from env if exists
@@ -230,28 +230,60 @@ function get_pools_raw {
 	send_request_to_miner_api '{"command":"pools"}'
 }
 
+function process_pools {
+	#
+	# !!! may change var from global scope: system_status
+	# !!! may change vars from outer scope: POOLS active_pool_id
+	#
+
+	# consts
+	local -r active_pool_id_RE='^[0-9]+$'
+
+	# vars
+	local pools_raw
+
+	# code
+	if pools_raw="$( get_pools_raw )"; then
+		if POOLS="$( jq --compact-output '.POOLS' <<< "$pools_raw" )"; then
+			if active_pool_id="$( jq --raw-output '[. as $object | keys[] | select($object[.]."Stratum Active" == true and $object[.]."Priority" <= 3) as $pool | select($object[$pool]."Getworks")] | .[0]' <<< "$POOLS" 2> /dev/null )"; then
+				if [[ "$active_pool_id" =~ $active_pool_id_RE ]]; then
+					: ok good to go
+				else
+					log_line error 'Active pool is dead:'
+					jq --color-output '.[0] | with_entries( select( .key | test( "Stratum Active", "URL", "User", "Status" ) ) )' <<< "$POOLS"
+					system_status='deadpool'
+					return 1
+				fi
+			else
+				log_line warning "No active pools yet"
+				return 1
+			fi
+		else
+			log_line warning "No pools yet"
+		fi
+	else
+		log_line warning "Failed to read pool stats from $miner_API_host:$miner_API_port"
+	fi
+}
+
 function get_miner_stats {
 	#
 	# Usage: get_miner_stats 'miner_name'
 	#
 
 	# args
-
 	local miner_name="$1"
 
 	# vars
-
 	local stats_raw max_fan_rpm STATS
 	local algo hs_units uptime hashrate_raw hashrate_raw_avg
-	local stats_pool_raw pool_stats active_pool
+	local POOLS active_pool_id
 	local hs temp chip_temp board_temp fan fan_rpm freq freq_new acn status chain_voltage hw_errors power asicboost ar
 
 	# arrays
-
 	local -a error_vars=() # must be empty
 
 	# traps
-
 	function sanitize_khs {
 		[[ -z "$khs"	]] && khs=0
 		[[ -z "$khs_av"	]] && khs_av=0
@@ -259,7 +291,6 @@ function get_miner_stats {
 	trap 'sanitize_khs' RETURN
 
 	# code
-
 	khs=0				# global
 	khs_av=0			# global
 	stats=''			# global
@@ -297,20 +328,7 @@ function get_miner_stats {
 
 				system_status="$( ant-functions hiveon_status "$STATS" )"
 
-				if stats_pool_raw="$( get_pools_raw )"; then
-					if pool_stats="$( jq --compact-output '.POOLS' <<< "$stats_pool_raw" )"; then
-						if active_pool="$( jq '[. as $object | keys[] | select($object[.]."Stratum Active" == true and $object[.]."Priority" <= 3) as $pool | select($object[$pool]."Getworks")] | .[0]' <<< "$pool_stats" 2> /dev/null )"; then
-							: ok good to go
-						else
-							log_line warning "No active pools yet"
-							return
-						fi
-					else
-						log_line warning "No pools yet"
-					fi
-				else
-					log_line warning "Failed to read pool stats from $miner_API_host:$miner_API_port"
-				fi
+				process_pools || return
 
 				uptime="$(			jq --raw-output		'.[1].Elapsed'																																<<< "$STATS" )"
 				hs="$(				jq --compact-output	'.[1] | with_entries( select(.key | test("chain_rate\\d+")) )		| to_entries | [ .[].value | if . != "" then tonumber else "" end  ]'	<<< "$STATS" 2> /dev/null )" || error_vars+=( "hs#$?" )
@@ -329,8 +347,8 @@ function get_miner_stats {
 #				power="$(			jq --compact-output	'.[1] | with_entries( select(.key | test("chain_power\\d+")) )		| to_entries | [ .[].value ]'											<<< "$STATS" 2> /dev/null )" || error_vars+=( "power#$?" )
 				power="$(			jq --compact-output	'.[1] | with_entries( select(.key | test("chain_power\\d+")) ) 		| to_entries | from_entries'											<<< "$STATS" 2> /dev/null )" || error_vars+=( "power#$?" )
 				asicboost="$(		jq					'.[1] | with_entries( select(.key | test("chain_power$")) )			| to_entries | .[].value | test("AB") | if . == true then 1 else 0 end'	<<< "$STATS" 2> /dev/null )" || error_vars+=( "asicboost#$?" )
-				ar="$(				jq --compact-output --arg pool "$active_pool" \
-														'.[$pool | tonumber] | with_entries( select(.key | test("^Accepted","^Rejected","Get Failures")) ) | to_entries | [.[].value]'				<<< "$pool_stats" 2> /dev/null )" || error_vars+=( "ar#$?" )
+				ar="$(				jq --compact-output --argjson pool "$active_pool_id" \
+														'.[$pool] | with_entries( select(.key | test("^Accepted","^Rejected","Get Failures")) ) | to_entries | [.[].value]'				<<< "$POOLS" 2> /dev/null )" || error_vars+=( "ar#$?" )
 
 				[[ "$chain_voltage" == '[]'	]] && chain_voltage="$( ant-functions hiveon_voltage <<< "$acn" )"
 				[[ "$power" != '{}'			]] && power="$( ant-functions hiveon_power "$power" "$acn" )"
@@ -383,20 +401,7 @@ function get_miner_stats {
 
 				system_status="$( ant-functions hiveon_status "$STATS" )"
 
-				if stats_pool_raw="$( get_pools_raw )"; then
-					if pool_stats="$( jq --compact-output '.POOLS' <<< "$stats_pool_raw" )"; then
-						if active_pool="$( jq '[. as $object | keys[] | select($object[.]."Stratum Active" == true and $object[.]."Priority" <= 3) as $pool | select($object[$pool]."Getworks")] | .[0]' <<< "$pool_stats" 2> /dev/null )"; then
-							: ok good to go
-						else
-							log_line warning "No active pools yet"
-							return
-						fi
-					else
-						log_line warning "No pools yet"
-					fi
-				else
-					log_line warning "Failed to read pool stats from $miner_API_host:$miner_API_port"
-				fi
+				process_pools || return
 
 				uptime="$(		jq --raw-output		'.[1].Elapsed'																															<<< "$STATS" )"
 				hs="$(			jq --compact-output	'.[1] | with_entries( select(.key | test("chain_rate\\d+")) )	| to_entries | [ .[].value | if . != "" then tonumber else "" end  ]'	<<< "$STATS" 2> /dev/null )" || error_vars+=( "hs#$?" )
@@ -410,8 +415,8 @@ function get_miner_stats {
 				power="$(		jq --compact-output	'.[1] | with_entries( select(.key | test("chain_power\\d+")) )	| to_entries | [.[].value]'												<<< "$STATS" 2> /dev/null )" || error_vars+=( "power#$?" )
 				status="$(		jq --compact-output	'.[1] | with_entries( select(.key | test("chain_acs\\d+")) )	| to_entries | [.[].value]'												<<< "$STATS" 2> /dev/null )" || error_vars+=( "status#$?" )
 				hw_errors="$(	jq --compact-output	'.[1] | with_entries( select(.key | test("chain_hw\\d+")) )		| to_entries | [.[].value]'												<<< "$STATS" 2> /dev/null )" || error_vars+=( "hw_errors#$?" )
-				ar="$(			jq --compact-output --arg pool "$active_pool" \
-													'.[$pool | tonumber] | with_entries( select(.key | test("^Accepted","^Rejected","Get Failures")) ) | to_entries | [.[].value]'			<<< "$pool_stats" 2> /dev/null )" || error_vars+=( "ar#$?" )
+				ar="$(			jq --compact-output --argjson pool "$active_pool_id" \
+													'.[$pool] | with_entries( select(.key | test("^Accepted","^Rejected","Get Failures")) ) | to_entries | [.[].value]'			<<< "$POOLS" 2> /dev/null )" || error_vars+=( "ar#$?" )
 
 				chain_voltage="$( ant-functions hiveon_voltage <<< "$acn" )"
 				miner_count="$( jq '. | length' <<< "$acn" )"
@@ -608,8 +613,7 @@ function get_miner_stats {
 				hashrate_raw="$( jq --raw-output '.[1]."GHS 5s"' <<< "$STATS" )" #14162.91 gh/s = 14 th/s
 				reduce_hashrate_to_khs "$hashrate_raw" "$HASH" khs
 
-				pool_stats="$( get_pools_raw | jq --compact-output '.POOLS' )"
-				active_pool="$(	jq '[. as $object | keys[] | select($object[.]."Stratum Active" == true and $object[.]."Priority" <= 3) as $pool | select($object[$pool]."Getworks")] | .[0]'	<<< "$pool_stats" )"
+				process_pools || return
 
 				uptime="$(		jq --raw-output		'.[1].Elapsed'																													<<< "$STATS" )"
 				hs="$(			jq --compact-output	'.[1]	| with_entries( select(.key | test("chain_rate\\d+")) )	| to_entries | [.[].value]'										<<< "$STATS" )" || error_vars+=( "hs#$?" )
@@ -624,8 +628,8 @@ function get_miner_stats {
 				acn="$(			jq --compact-output	'.[1]	| with_entries( select(.key | test("chain_acn\\d+")) )	| to_entries | [.[].value]'										<<< "$STATS" )" || error_vars+=( "acn#$?" )
 				status="$(		jq --compact-output	'.[1]	| with_entries( select(.key | test("chain_acs\\d+")) )	| to_entries | [.[].value]'										<<< "$STATS" )" || error_vars+=( "status#$?" )
 				hw_errors="$(	jq --compact-output	'.[1]	| with_entries( select(.key | test("chain_hw\\d+")) )	| to_entries | [.[].value]'										<<< "$STATS" )" || error_vars+=( "hw_errors#$?" )
-				ar="$(			jq --compact-output --arg pool "$active_pool" \
-									'.[$pool | tonumber] | with_entries( select(.key | test("^Accepted","^Rejected","Get Failures")) ) | to_entries | [.[].value]'	<<< "$pool_stats" )" || error_vars+=( "ar#$?" )
+				ar="$(			jq --compact-output --argjson pool "$active_pool_id" \
+									'.[$pool] | with_entries( select(.key | test("^Accepted","^Rejected","Get Failures")) ) | to_entries | [.[].value]'	<<< "$POOLS" )" || error_vars+=( "ar#$?" )
 
 				if [[ "$( jq --raw-output length <<< "$freq" )" -ne "$miner_count" ]]; then
 					freq_new='[]'
@@ -931,7 +935,9 @@ function loop {
 			rm "$last_cmd_id_FILE"
 		fi
 	else
-		log_line info "Server answer: $( jq --compact-output --color-output '.result' <<< "$response" )"
+		local response_stripped="${response//\\n/\\\\n}" # neuter the \n's
+		log_line info "Server answer: $( jq --compact-output --color-output '.result' <<< "$response_stripped" )"
+		echo
 		skip_the_sleep=1
 	fi
 
@@ -1211,6 +1217,7 @@ function do_command {
 				if [[ "$justwrite" != 1 ]]; then
 					#hostname-check
 					/hive/bin/miner restart
+					echo
 				fi
 
 				# Start Watchdog. It will exit if WD_ENABLED=0 ---------------------------
