ADD FPGA Blackminer F1 series by HashAltCoin

diff --git a/hive/bin/agent b/hive/bin/agent
--- a/hive/bin/agent
+++ b/hive/bin/agent
@@ -395,6 +395,76 @@ miner_stats () {
 					'{$algo, $hs, $hs_units, ar: ['$ac', '$rj'], $hw_errors, $acn, $freq, $temp, $fan, $fan_rpm, $power, $status, $uptime}')
 				[[ "$khs" -gt 1 ]] && system_status="mining"
 		;;
+
+		"Blackminer F1"*)
+			stats_raw=`echo '{"command":"stats"}' | timeout -t 7 nc localhost 4028 | tr -d '\0'`
+			if [[ $? -ne 0 || -z $stats_raw ]]; then
+				echo -e "${YELLOW}Failed to read $miner stats from localhost:4028${NOCOLOR}"
+			else
+				stats_raw=$(sed 's/}{/\},{/' <<< "$stats_raw")
+				local STATS=$(jq '.STATS' <<< "$stats_raw")
+				local COIN=$(cat /config/cgminer.conf | jq -r '."coin-type"')
+                                POWER=(50)
+				[[ -e /hive/share/blackminer/blackminer.json ]] && BBDATA=`cat /hive/share/blackminer/blackminer.json | jq -e '.'`
+                                if [[ "$?" -eq 0 ]]; then
+                                   ASIC_ALGO=`echo $BBDATA | jq -r --arg coin "$COIN" '.[$coin].algo'`
+                                   POWER=`echo $BBDATA | jq -r --arg coin "$COIN" '.[$coin].power'`
+                                fi
+                 
+                                ##echo $ASIC_ALGO $POWER
+				#if [[ -z $algo || $algo == "null" ]]; then
+				#	algo=`echo '{"command":"coin"}' | nc localhost 4028 | jq '.COIN."Hash Method"'`
+				#fi
+
+				local algo=$ASIC_ALGO
+				local hs_units=$HASH
+				local uptime=$(jq -r '.[1].Elapsed' <<< "$STATS")
+				khs=$(jq -r '.[1]."GHS 5s"' <<< "$STATS") #14162.91 gh/s = 14 th/s
+				if [[ $HASH == "mhs" ]]; then
+					khs=$(awk '{print $1 * 1000}' <<< "$khs")
+				elif [[ $HASH == "khs" ]]; then
+					khs=$(awk '{print $1}' <<< "$khs")
+				else
+					khs=$(awk '{print $1 * 1000000}' <<< "$khs")
+				fi
+
+				local stats_pool=`echo '{"command":"pools"}' | timeout -t 7 nc localhost 4028 | tr -d '\0' | jq '.POOLS'`
+				local active_pool=$(echo $stats_pool | jq '[. as $object | keys[] | select($object[.]."Stratum Active" == true  and $object[.]."Priority" <= 3) as $pool | select($object[$pool]."Getworks")] | .[0]')
+
+				local hs=$( 	 (jq '.[1] | with_entries( select(.key | test("chain_rate\\d+")) ) 	| to_entries | [.[].value]') <<< "$STATS" )
+#				local temp=$(	 (jq '.[1] | with_entries( select(.key | test("temp2_\\d+")) ) 		| to_entries | [.[].value]') <<< "$STATS")
+				local temp=$((jq '.[1] | with_entries( select(.key | test("temp\\d+$")) ) 	| to_entries | [.[].value]') <<< "$STATS")
+				local board_temp=$((jq '.[1] | with_entries( select(.key | test("temp\\d+$")) ) 	| to_entries | [.[].value]') <<< "$STATS")
+				local fan=$(	 (jq '.[1] | with_entries( select(.key | test("fan\\d+")) ) 		| to_entries | [.[].value / '$max_fan_rpm' * 100 ]') <<< "$STATS")
+				local fan_rpm=$( (jq '.[1] | with_entries( select(.key | test("fan\\d+")) ) 		| to_entries | [.[].value]') <<< "$STATS")
+				local freq=$(	 (jq '.[1] | with_entries( select(.key | test("frequency\\d+")) )       | to_entries | [.[].value]') <<< "$STATS")
+				local miner_count=$((jq '.[1] | with_entries( select(.key | test("miner_count")) )      | to_entries | .[].value') <<< "$STATS")
+				local acn=$(	 (jq '.[1] | with_entries( select(.key | test("chain_acn\\d+")) ) 	| to_entries | [.[].value]') <<< "$STATS")
+				local status=$(	 (jq '.[1] | with_entries( select(.key | test("chain_acs\\d+")) ) 	| to_entries | [.[].value]') <<< "$STATS")
+				local hw_errors=$( (jq '.[1] | with_entries( select(.key | test("chain_hw\\d+")) ) 	| to_entries | [.[].value]') <<< "$STATS")
+				local ar=$(	 (jq -c --arg pool "$active_pool" '.[$pool|tonumber] | with_entries( select(.key | test("^Accepted","^Rejected","Get Failures")) ) | to_entries | [.[].value]') <<< "$stats_pool")
+
+				if [ $(echo $freq | jq -r length) -ne "$miner_count" ]; then
+					local freq_new="[]"
+					local freq=$((jq '.[1] | with_entries( select(.key | test("frequency")) )       | to_entries | [.[].value]') <<< "$STATS")
+					local freq_num=$(echo $freq | jq -r .[0])
+					for (( c=1; c<=$miner_count; c++ )); do
+						freq_new=$(echo "$freq_new" | jq -r --arg freq_num "$freq_num" '[.[], $freq_num|tonumber]')
+					done
+				else freq_new=$freq
+				fi
+                                
+				stats=$(jq -nc \
+						--arg algo "$algo" --argjson hs "$hs" --arg hs_units "$hs_units" \
+						--argjson temp "$temp" --argjson board_temp "$board_temp" --argjson fan "$fan" --argjson fan_rpm "$fan_rpm" \
+						--argjson freq "$freq_new" --argjson acn "$acn" \
+						--argjson power "`echo $POWER | jq -cs '.'`" --argjson ar "$ar" \
+						--argjson hw_errors "$hw_errors" --argjson status "$status" \
+						--arg uptime "$uptime" \
+						'{$algo, $hs, $hs_units, $temp, $board_temp, $fan, $fan_rpm, $freq, $acn, $power, $ar, $hw_errors, $status, $uptime}')
+			fi
+		;;
+
 		
 		*)
 			miner="unknown"
