FIX agent-screen
* reworked screen_start_session()/screen_stop_session()
* fixed some minor bugs

diff --git a/hive/bin/agent-screen b/hive/bin/agent-screen
--- a/hive/bin/agent-screen
+++ b/hive/bin/agent-screen
@@ -9,7 +9,7 @@
 
 
 readonly script_mission='Client for ASICs: agent-screen helper'
-readonly script_version='1.0.9'
+readonly script_version='1.0.10'
 readonly script_basename="$( basename "$0" )"
 readonly DEBUG=0
 
@@ -34,38 +34,28 @@ function errcho {
 # functions: screen
 
 function is_screen_session_exist {
-	# is_screen_session_exist 'session name'
+	# Usage: is_screen_session_exist 'session name' -> $?
 
 	# args
-
 	(( $# == 1 )) || { errcho 'only 1 argument allowed'; return $(( exitcode_ERROR_IN_ARGUMENTS )); }
-
 	local -r session_name="${1-}"
-	local -i screen_exitcode="$exitcode_OK"
 
 	# code
-
 	if (( DEBUG )); then
 		screen -S "$session_name" -X select .
 	else
 		screen -S "$session_name" -X select . > /dev/null
 	fi
-	screen_exitcode=$?
-
-	return $(( screen_exitcode ))
 }
 
 function screen_attach_to_session {
-	# screen_attach_to_session 'session name'
+	# Usage: screen_attach_to_session 'session name'
 
 	# args
-
 	(( $# == 1 )) || { errcho 'only 1 argument allowed'; return $(( exitcode_ERROR_IN_ARGUMENTS )); }
-
 	local -r session_name="${1-}"
 
 	# code
-
 	if is_screen_session_exist "$session_name"; then
 		#
 		# why setting TERM in such a fashion? screen has an argument for that:
@@ -83,37 +73,33 @@ function screen_attach_to_session {
 }
 
 function screen_start_session {
-	# screen_start_session 'cmd' [args...]
+	# Usage: screen_start_session 'cmd' [args...]
 
 	# args
-
 	(( $# > 0 )) || { errcho 'no arguments given'; return $(( exitcode_ERROR_IN_ARGUMENTS )); }
-
 	local -r cmd="${1-}"
 	local -r args="${*:2}"
 
 	# consts
-
 	local -r session_name="$cmd"
 	local -r -i retries_limit=100
 	local -r -i scrollback_buffer_lines=200
 
 	# vars
-
 	local -i retries_counter
-	local -i function_exitcode="$exitcode_OK"
+	local -i function_exitcode=$(( exitcode_OK ))
 
 	# code
-
 	if ! which "$cmd" > /dev/null; then
 		errcho "cannot locate command '$cmd' to run in the screen session"
 		return $(( exitcode_ERROR_CMD_NOT_FOUND ))
 	fi
 
-	retries_counter=0
+	retries_counter=1
 	until is_screen_session_exist "$session_name"; do
-		if (( retries_counter > 0 )); then
+		if (( retries_counter > 1 )); then
 			{ sleep 0.5 || usleep 500000 || sleep 1; } 2> /dev/null # only integer sleep on BusyBox
+			screen -wipe # > /dev/null # let's debug
 		#else
 			# skip 'sleep' at the first iteration
 		fi
@@ -124,47 +110,52 @@ function screen_start_session {
 			screen -dm -S "$session_name" -h "$scrollback_buffer_lines" "$cmd" $args > /dev/null
 		fi
 
-		(( retries_counter++ ))
+		(( retries_counter == 2 )) && printf '\n'
 
 		if (( retries_counter % 10 == 0 )); then
-			[[ -t 1 ]] && printf '\r'
-			printf 'Waiting for %s screen session to start... Attempt #%d' "$session_name" "$retries_counter"
+			if [[ -t 1 ]]; then
+				printf '\rWaiting for %s screen session to start, attempt #%d... ' "$session_name" "$retries_counter"
+			else
+				printf 'Waiting for %s screen session to start, attempt #%d... \n' "$session_name" "$retries_counter"
+			fi
 		fi
 
 		if (( retries_counter >= retries_limit )); then
 			[[ -t 1 ]] && printf '\n'
 			errcho "'$session_name' hasn't been started. Weird..."
-			function_exitcode="$exitcode_ERROR_SOMETHING_BAD_HAPPEN"
+			# debug
+			ls -ALl /var/run/screens
+			screen -ls
+			ps w | grep "[${session_name::1}]${session_name:1}" # surround the first char in [b]rackets, neat
+			#
+			(( function_exitcode = exitcode_ERROR_SOMETHING_BAD_HAPPEN ))
 			break
 		fi
+
+		(( retries_counter++ ))
 	done
 
 	return $(( function_exitcode ))
 }
 
 function screen_stop_session {
-	# screen_stop_session 'session name' -> $?
+	# Usage: screen_stop_session 'session name' -> $?
 
 	# args
-
 	(( $# > 0 )) || { errcho 'no arguments given'; return $(( exitcode_ERROR_IN_ARGUMENTS )); }
-
 	local -r session_name="${1-}"
 
 	# consts
-
 	local -r -i retries_limit=100
 
 	# vars
-
 	local -i retries_counter
-	local -i function_exitcode="$exitcode_OK"
+	local -i function_exitcode=$(( exitcode_OK ))
 
 	# code
-
-	retries_counter=0
+	retries_counter=1
 	while is_screen_session_exist "$session_name"; do
-		if (( retries_counter > 0 )); then
+		if (( retries_counter > 1 )); then
 			{ sleep 0.5 || usleep 500000 || sleep 1; } 2> /dev/null # only integer sleep on BusyBox
 		#else
 			# skip 'sleep' at the first iteration
@@ -176,11 +167,14 @@ function screen_stop_session {
 			screen -S "$session_name" -X quit > /dev/null
 		fi
 
-		(( retries_counter++ ))
+		(( retries_counter == 2 )) && printf '\n'
 
 		if (( retries_counter % 10 == 0 )); then
-			[[ -t 1 ]] && printf '\r'
-			printf 'Waiting for %s screen session to stop... Attempt #%d' "$session_name" "$retries_counter"
+			if [[ -t 1 ]]; then
+				printf '\rWaiting for %s screen session to stop, attempt #%d... ' "$session_name" "$retries_counter"
+			else
+				printf 'Waiting for %s screen session to stop, attempt #%d... \n' "$session_name" "$retries_counter"
+			fi
 			rm -rf /var/run/screens/*."$session_name"
 			screen -wipe
 		fi
@@ -188,10 +182,18 @@ function screen_stop_session {
 		if (( retries_counter >= retries_limit )); then
 			[[ -t 1 ]] && printf '\n'
 			errcho "cannot stop '$session_name' in $retries_limit attempts. Zombie screen session?"
-			{ ls -ALl /var/run/screens/*; ps w; } | message warn 'screen session goes zombie, please contact support' payload
-			function_exitcode="$exitcode_ERROR_SOMETHING_BAD_HAPPEN"
+			{
+				# debug
+				ls -ALl /var/run/screens
+				screen -ls
+				ps w | grep "[${session_name::1}]${session_name:1}" # surround the first char in [b]rackets, neat
+			} | tee >( message warn 'agent screen session goes zombie, please contact support (and do not erase this message)' payload )
+			#
+			(( function_exitcode = exitcode_ERROR_SOMETHING_BAD_HAPPEN ))
 			break
 		fi
+
+		(( retries_counter++ ))
 	done
 
 	return $(( function_exitcode ))
@@ -201,32 +203,30 @@ function screen_stop_session {
 
 function agent_start {
 	# args
-
 	local -r message_mode="${1-}"
 
 	# code
-
 	if ! is_screen_session_exist 'agent'; then
-		echo -n "${script_basename}> Starting new agent screen session... "
-		screen_start_session 'agent' && echo 'Started.' || echo 'Error.'
+		echo -n "${script_basename}> Starting agent... "
+		screen_start_session 'agent' && echo 'Started.' || printf '\n%s: %s\n' "$script_basename" 'Session starting error'
 	else
 		if [[ $message_mode != '--quiet-ok' ]]; then
-			echo "${script_basename}: Agent screen session is already running"
+			echo "${script_basename}: Agent is already running"
 		fi
 	fi
 }
 
 function agent_stop {
 	if is_screen_session_exist 'agent'; then
-		echo -n "${script_basename}> Stopping agent screen session... "
-		screen_stop_session 'agent' && echo 'Stopped.' || echo 'Error.'
+		echo -n "${script_basename}> Stopping agent... "
+		screen_stop_session 'agent' && echo 'Stopped.' || printf '\n%s: %s\n' "$script_basename" 'Session stopping error'
 	else
-		echo "${script_basename}: Agent screen session hasn't been running"
+		echo "${script_basename}: Agent hasn't been running"
 	fi
 }
 
 function agent_restart {
-	echo "${script_basename}> Restarting agent screen session"
+	echo "${script_basename}> Restarting agent"
 	agent_stop
 	agent_start
 }
