Innosilicon A5/A8

diff --git a/hive/bin/agent b/hive/bin/agent
--- a/hive/bin/agent
+++ b/hive/bin/agent
@@ -213,6 +213,45 @@ miner_stats () {
 						'{$algo, $hs, $hs_units, $temp, $fan, $freq, $acn, $hw_errors, $status, $uptime}')
 			fi
 		;;
+		"T4.G19")
+			stats_raw=`echo '{"command":"devs"}' | timeout -t 7 nc localhost 4028 | tr -d '\0'`
+			if [[ $? -ne 0 || -z $stats_raw ]]; then
+				echo -e "${YELLOW}Failed to read $miner stats from localhost:4028${NOCOLOR}"
+			else
+				local STATS=$(jq '.DEVS' <<< "$stats_raw")
+
+				#if [[ -z $algo || $algo == "null" ]]; then
+				#	algo=`echo '{"command":"coin"}' | nc localhost 4028 | jq '.COIN."Hash Method"'`
+				#fi
+
+				local algo=$ASIC_ALGO
+				local hs_units=$HASH
+				local uptime=$(jq -r '.[0]["Device Elapsed"]' <<< "$STATS")
+				khs=$(jq -r '[.[]["MHS av"]] | add' <<< "$STATS")
+				if [[ $HASH == "mhs" ]]; then
+					khs=$(awk '{print $1 * 1000}' <<< "$khs")
+				elif [[ $HASH == "khs" ]]; then
+					khs=$(awk '{print $1}' <<< "$khs")
+				else
+					khs=$(awk '{print $1 / 1000}' <<< "$khs")
+				fi
+
+				local hs=$(	 (jq '[.[] | with_entries( select(.key | test("MHS 5s")) ) 		| to_entries | .[].value]') <<< "$STATS")
+				local temp=$(	 (jq '[.[] | with_entries( select(.key | test("TempAVG")) ) 		| to_entries | .[].value]') <<< "$STATS")
+				local freq=$(	 (jq '[.[] | with_entries( select(.key | test("CORE")) ) 		| to_entries | .[].value]') <<< "$STATS")
+				local acn=$(	 (jq '[.[] | with_entries( select(.key | test("DUTY")) ) 		| to_entries | .[].value]') <<< "$STATS")
+#				local status=$(	 (jq '[.[] | with_entries( select(.key | test("Num active chips")) ) 	| to_entries | .[].value]') <<< "$STATS")
+				local hw_errors=$( (jq '[.[] | with_entries( select(.key | test("Hardware Errors")) ) 	| to_entries | .[].value]') <<< "$STATS")
+
+				stats=$(jq -nc \
+						--arg algo "$algo" --argjson hs "$hs" --arg hs_units "$hs_units" \
+						--argjson temp "$temp" \
+						--argjson freq "$freq" --argjson acn "$acn" \
+						--argjson hw_errors "$hw_errors" \
+						--arg uptime "$uptime" \
+						'{$algo, $hs, $hs_units, $temp, $freq, $acn, $hw_errors, $uptime}')
+			fi
+		;;
 		*)
 			miner="unknown"
 			#MINER=miner
diff --git a/hive/bin/selfupgrade b/hive/bin/selfupgrade
--- a/hive/bin/selfupgrade
+++ b/hive/bin/selfupgrade
@@ -244,6 +244,62 @@ install_innosilicon() {
 }
 
 
+
+install_innosilicon_innominer() {
+	echo ""
+	mount -o remount,rw,relatime -t jffs2 /dev/root /
+
+	echo "> Extracting $filename"
+	[ ! -d /hive ] && mkdir /hive
+	tar -xzv -f $filename
+	cp -rf hiveos-asic-$release/hive-config /innocfg/
+	cp -rf hiveos-asic-$release/hive /
+#	cp -rf hiveos-asic-$release/home/root/.profile /etc/profile.d/hive.sh
+	[ $? -ne 0 ] && echo "Error extracting $filename" && exit 1
+	rm $filename
+
+	[ ! -L /hive-config ] && [ ! -e /hive-config ] && ln -s /innocfg/hive-config/ /hive-config
+
+	#autorun
+	if grep "### HIVE AUTORUN ###" /etc/init.d/rcS; then
+		echo "/etc/init.d/rcS skip"
+	else
+		cat >> /etc/init.d/rcS <<FILEEOF
+
+### HIVE AUTORUN ###
+[ -e /hive/bin/hive ] && nohup /hive/sbin/bash -c 'sleep 30; /hive/bin/hive > /tmp/hive-boot.log; echo "Running hive..."' > /dev/null 2>&1 &
+[ -e /hive/bin/hello ] && nohup /hive/sbin/bash -c 'sleep 40; /hive/bin/hello' > /dev/null 2>&1 &
+[ -e /hive/bin/cron1 ] && nohup /hive/sbin/bash -c 'sleep 60; /hive/bin/cron1' > /dev/null 2>&1 &
+[ -e /hive/bin/cron2 ] && nohup /hive/sbin/bash -c 'sleep 60; /hive/bin/cron2' > /dev/null 2>&1 &
+FILEEOF
+	fi
+
+	#PATH
+	if grep "### HIVE PROFILE ###" /etc/profile; then
+		echo "/etc/profile skip"
+	else
+		cat >> /etc/profile <<FILEEOF
+
+### HIVE PROFILE ###
+export PATH=$PATH:/hive/bin:/hive/sbin
+export LD_LIBRARY_PATH=/hive/lib
+FILEEOF
+	fi
+
+	export PATH=$PATH:/hive/bin:/hive/sbin
+	export LD_LIBRARY_PATH=/hive/lib
+
+	sync
+	sleep 5
+	mount -o remount,ro,relatime -t jffs2 /dev/root /
+
+	/hive/bin/hive
+	#$FARM_HASH can be defined externally
+	bash -c "/hive/bin/firstrun $FARM_HASH"
+}
+
+
+
 install_zig() {
 	echo ""
 	echo "> Extracting $filename"
