Microbt WhatsMiner M10

diff --git a/hive/bin/agent b/hive/bin/agent
--- a/hive/bin/agent
+++ b/hive/bin/agent
@@ -25,7 +25,7 @@ screen_count=`screen -ls | grep "\.agent" | grep -v $PPID | wc -l`
 
 . asic-model
 echo -e "Detected ASIC model: ${CYAN}$ASIC_MODEL${NOCOLOR}\n"
-[[ $WD_ENABLED=1 ]] && nohup wd stop && nohup sleep 5; wd start &
+[[ $WD_ENABLED=1 ]] && nohup wd stop > /tmp/nohup.out && nohup sleep 5 > /tmp/nohup.out; wd start &
 
 ########################################################################################################################
 
@@ -144,6 +144,48 @@ miner_stats () {
 						--argjson hw_errors "$hw_errors" --argjson status "$status" \
 						--arg uptime "$uptime" \
 						'{$algo, $hs, $hs_units, $temp, $board_temp, $fan, $fan_rpm, $freq, $acn, $hw_errors, $status, $uptime}')
+			fi
+		;;
+		"WhatsMiner M10")
+			stats_raw=`echo '{"command":"edevs"}' | timeout -t 7 nc localhost 4028 | tr -d '\0'`
+			if [[ $? -ne 0 || -z $stats_raw ]]; then
+				echo -e "${YELLOW}Failed to read $miner stats from localhost:4028${NOCOLOR}"
+			else
+				stats_raw=$(sed 's/}{/\},{/' <<< "$stats_raw")
+				local STATS=$(jq '.DEVS' <<< "$stats_raw")
+
+				local algo=$ASIC_ALGO
+				local hs_units=$HASH
+				local uptime=$(jq -r '.[0]."Device Elapsed"' <<< "$STATS")
+				khs=$(jq -r '[.[] | with_entries( select(.key == "MHS 5s") ) | to_entries | [.[].value] | add] | add' <<< "$STATS")
+				if [[ $HASH == "mhs" ]]; then
+					khs=$(awk '{print $1 * 1000}' <<< "$khs")
+				elif [[ $HASH == "khs" ]]; then
+					khs=$(awk '{print $1 * 1}' <<< "$khs")
+				else
+					khs=$(awk '{print $1 * 1000000}' <<< "$khs")
+				fi
+
+				local stats_pool=`echo '{"command":"pools"}' | timeout -t 7 nc localhost 4028 | tr -d '\0' | jq '.POOLS'`
+				local active_pool=$(echo $stats_pool | jq '[. as $object | keys[] | select($object[.]."Stratum Active" == true ) as $pool | select($object[$pool]."Getworks")] | .[0]')
+
+				local hs=$( 	 (jq '[.[] | with_entries( select(.key == "MHS 5s") ) 			| to_entries | .[].value]') <<< "$STATS" )
+				local temp=$(	 (jq '[.[] | with_entries( select(.key == "Temperature") ) | to_entries | .[].value]') <<< "$STATS")
+				local fan=$(	 (jq '[.[0] | with_entries( select(.key == "Fan Speed In" or .key == "Fan Speed Out") ) | to_entries | .[].value / '$max_fan_rpm' * 100 ]') <<< "$STATS")
+				local fan_rpm=$( (jq '[.[0] | with_entries( select(.key == "Fan Speed In" or .key == "Fan Speed Out") ) | to_entries | .[].value]') <<< "$STATS")
+				local freq=$(	 (jq '[.[] | with_entries( select(.key == "Chip Frequency") ) | to_entries | .[].value]') <<< "$STATS")
+				local acn=$(	 (jq '[.[] | with_entries( select(.key == "Effective Chips") ) | to_entries | .[].value]') <<< "$STATS")
+				local status=$(	 (jq '[.[] | with_entries( select(.key == "Effective Chips") ) | to_entries | .[].value]') <<< "$STATS")
+				local hw_errors=$( (jq '[.[] | with_entries( select(.key == "Hardware Errors") ) | to_entries | .[].value]') <<< "$STATS")
+				local ar=$(	 (jq -c --arg pool "$active_pool" '.[$pool|tonumber] | with_entries( select(.key == "Accepted" or .key == "Rejected" or .key == "Get Failures") ) | to_entries | [.[].value]') <<< "$stats_pool")
+
+				stats=$(jq -nc \
+						--arg algo "$algo" --argjson hs "$hs" --arg hs_units "$hs_units" \
+						--argjson temp "$temp" --argjson fan "$fan" --argjson fan_rpm "$fan_rpm" \
+						--argjson freq "$freq" --argjson acn "$acn" \
+						--argjson hw_errors "$hw_errors" --argjson status "$status" \
+						--arg uptime "$uptime" --argjson ar "$ar"\
+						'{$algo, $hs, $hs_units, $temp, $fan, $fan_rpm, $freq, $acn, $hw_errors, $status, $uptime, $ar}')
 			fi
 		;;
 		"Zig Z1+"|"Zig Z1")
@@ -299,8 +341,11 @@ loop () {
 
 	echo -en "Hashrate ${CYAN}$MINER${NOCOLOR} `[[ $khs > 0 ]] && echo -e ${YELLOW} || echo -e ${RED}`$khs${NOCOLOR} kH/s"
 	echo -en "\n"
-	echo $khs > /run/hive/khs
-
+	if [ -d /run/ ]; then
+		echo $khs > /run/hive/khs
+	else
+		echo $khs > /tmp/khs
+	fi
 
 	#echo $stats
 	#uptime: load averages for the past 1, 5, and 15 minutes
@@ -506,7 +551,7 @@ do_command () {
 				fi
 
 				# Start Watchdog. It will exit if WD_ENABLED=0 ---------------------------
-				[[ $WD_ENABLED=1 ]] && nohup wd stop && nohup sleep 5; wd start &
+				[[ $WD_ENABLED=1 ]] && nohup wd stop > /tmp/nohup.out && nohup sleep 5> /tmp/nohup.out ; wd start &
 
 				message ok "Rig config changed" --id=$cmd_id
 				#[[ $? == 0 ]] && message ok "Wallet changed, miner restarted" --id=$cmd_id || message warn "Error restarting miner" --id=$cmd_id
diff --git a/hive/bin/selfupgrade b/hive/bin/selfupgrade
--- a/hive/bin/selfupgrade
+++ b/hive/bin/selfupgrade
@@ -6,18 +6,23 @@
 [ -e "/var/www/html/src/Template/Layout/signin.twig" ] && ASIC_MODEL=`cat /var/www/html/src/Template/Layout/signin.twig | grep title | sed 's/<[^>]*>//g' | sed s/\ *//` #Zig old firmware
 [ -e "/var/www/html/src/Template/Layout/signin.twig" ] && [ -e "/var/www/html/TYPE" ] && ASIC_MODEL=$(echo $ASIC_MODEL | sed s/"{{ type() }}"/$(cat /var/www/html/TYPE)/) #Zig new firmware
 [ -e "/tmp/type" ] && [ ! -e "/etc/hwrevision" ] && ASIC_MODEL=`cat /tmp/type`.`cat /tmp/hwver` #Innosilicon A5/8
+[ -e "/tmp/miner-info" ] && ASIC_MODEL=`cat /tmp/miner-info` #WhatsMiner
 echo $ASIC_MODEL
 
-if [ "$ASIC_MODEL" == "Zig Z1+" ] || [ "$ASIC_MODEL" == "Zig Z1" ]; then
+if [ "$ASIC_MODEL" == "Zig Z1+" ] || [ "$ASIC_MODEL" == "Zig Z1" ] || echo "$ASIC_MODEL" | grep -q -s -F "WhatsMiner"; then
 	release=`wget -q -O- https://raw.githubusercontent.com/minershive/hiveos-asic/master/hive/etc/VERSION`
 else
 	release=`curl -f --silent -L --insecure https://raw.githubusercontent.com/minershive/hiveos-asic/master/hive/etc/VERSION`
 fi
 
+#DEL!!!
+release=whatsminer
+
 exitcode=$?
 version=0
 [ -e /hive/etc/VERSION ] && version=`cat /hive/etc/VERSION`
-filename=v$release.tar.gz
+#filename=v$release.tar.gz #RESTORE!!!
+filename=$release.tar.gz
 
 t=`df -h | grep  '/tmp' | awk '{print $NF}'`
 [ -z $t ] && t='/tmp'
@@ -57,8 +62,8 @@ url=http://github.com/minershive/hiveos-asic/archive/$filename
 echo $url
 
 echo "> Downloading $url"
-if [ "$ASIC_MODEL" == "Zig Z1+" ] || [ "$ASIC_MODEL" == "Zig Z1" ]; then
-	wget $url
+if [ "$ASIC_MODEL" == "Zig Z1+" ] || [ "$ASIC_MODEL" == "Zig Z1" ] || echo "$ASIC_MODEL" | grep -q -s -F "WhatsMiner"; then
+	wget $url -O $filename
 else
 	curl -L --insecure -O $url
 fi
@@ -345,6 +350,39 @@ install_zig() {
 	bash -c "/hive/bin/firstrun $FARM_HASH"
 }
 
+install_whatsminer() { # whatsminer, / - ro
+	echo ""
+	mount -o remount,rw,noatime,nodiratime,nodelalloc,data=journal -t ext4 /
+	echo "> Extracting $filename"
+	if [ ! -d /data/hive ]; then
+		mkdir -p /data/hive/hive-config
+	fi
+	tar -xzv -f $filename
+	rm -rf hiveos-asic-$release/hive/sbin/teleconsole
+	cp -rf hiveos-asic-$release/hive /
+        mv -f /hive/share/whatsminer/sbin/* /hive/sbin/
+	[ $? -ne 0 ] && echo "Error extracting $filename" && exit 1
+
+	rm $filename
+	sync
+
+	export PATH=$PATH:/hive/bin:/hive/sbin
+	export LD_LIBRARY_PATH=/hive/lib
+
+	if [ ! -e /hive-config ]; then
+		ln -s /data/hive/hive-config/ /hive-config
+	fi
+	cp -rf /hive/share/whatsminer/S99hive /etc/rc.d/
+	cp -rf /hive/share/S9/.profile /root/
+	sync
+	mount -o remount,ro,noatime,nodiratime,nodelalloc,data=journal -t ext4 /
+
+	/hive/bin/hive
+
+	#$FARM_HASH can be defined externally
+	bash -c "/hive/bin/firstrun $FARM_HASH"
+}
+
 
 
 if [ "$ASIC_MODEL" == "Antminer S9" ]; then
@@ -368,6 +406,9 @@ elif echo "$ASIC_MODEL" | grep -q -s -F "Antminer S9 (vnish"; then
 elif echo "$ASIC_MODEL" | grep -q -s -F "Antminer S9"; then
 	echo "Install Antminer S9"
 	install_antminer_bmminer
+elif echo "$ASIC_MODEL" | grep -q -s -F "WhatsMiner"; then
+	echo "Install WhatsMiner"
+	install_whatsminer
 elif [ "$ASIC_MODEL" == "Antminer " ]; then
 	echo "Install Antminer B3"
 	install_antminer_bmminer
