firmware upgrade small fix

diff --git a/hive/bin/agent b/hive/bin/agent
--- a/hive/bin/agent
+++ b/hive/bin/agent
@@ -432,6 +432,17 @@ do_command () {
 					echo "$payload" | message error "Overclock config failed" payload --id='$cmd_id'
 			'
 		;;
+		firmware-upgrade)
+			export firmware_url=`echo $body | jq '.firmware_url' --raw-output`
+			screen -dm -S upgade bash -c '
+				firmware-upgrade $firmware_url 2>&1 | tee /tmp/nohup.log
+				exitcode=${PIPESTATUS[0]}
+				payload=`cat /tmp/nohup.log`
+					[[ $exitcode -eq 0 ]] &&
+					echo "$payload" | message ok "Firmware upgrade successful, rebooting..." payload --id='$cmd_id' ||
+					echo "$payload" | message error "Firmware upgrade failed" payload --id='$cmd_id'
+			'
+		;;
 		config)
 			config=$(echo $body | jq '.config' --raw-output)
 			justwrite=$(echo $body | jq '.justwrite' --raw-output) #don't restart miner, just write config, maybe WD settings will be updated
