UPDATE asic-oc
* refactored a bit (also a code style)
* improved restore_cached_profile() -- restoring of frequency/voltage parameters from cached config.conf
* remade deactivate_active_profile_files() to a base function plus two wrappers

diff --git a/hive/bin/asic-oc b/hive/bin/asic-oc
--- a/hive/bin/asic-oc
+++ b/hive/bin/asic-oc
@@ -11,9 +11,8 @@
 
 
 readonly script_mission='Client for ASICs: Antminer overclock profiles management'
-readonly script_version='0.6.39'
+readonly script_version='0.7.0'
 readonly script_basename="${0##*/}"
-#
 readonly script_DEBUG="${script_DEBUG:-1}" # use value from env if exists
 
 
@@ -158,9 +157,7 @@ function process_arguments {
 
 function is_series_17 {
 	# code
-	# shellcheck disable=SC2076
-	[[ "$ASIC_MODEL" =~ 'Antminer S17' || "$ASIC_MODEL" =~ 'Antminer T17' ]]
-	# ...bc we need a literal match
+	[[ "$ASIC_MODEL" == 'Antminer S17'* || "$ASIC_MODEL" == 'Antminer T17'* ]]
 }
 
 function is_profile_cached {
@@ -456,8 +453,12 @@ function restore_cached_profile {
 	(( $# == 1 )) || return 1
 	local -r profile_id="$1"
 
+	# REs
+	local -r hiveon_freq_and_voltage_RE='^bitmain-freq|^bitmain-voltage'
+
 	# vars
 	local this_file source_file destination_file
+	local fv_settings_from_source_config non_fv_settings_from_destination_config
 	local -i is_something_restored_FLAG=0
 
 	# code
@@ -467,10 +468,27 @@ function restore_cached_profile {
 		source_file="$cached_profiles_directory/$profile_id/$this_file"
 		destination_file="$active_profile_directory/$this_file"
 		if [[ -s "$source_file" ]]; then
-			# cp -p: preserve timestamp
-			if cp -pf "$source_file" "$destination_file"; then
-				(( script_DEBUG )) && echo "  [DEBUG] copying $source_file to $active_profile_directory/..."
-				is_something_restored_FLAG=1
+			if [[ "$this_file" == "$hiveon_config_file" ]]; then
+				# get hashboard freq/voltage settings from cached hiveon config and then paste them in the current hiveon config
+				# NOTE: the other settings in the current config should be left intact
+				if fv_settings_from_source_config="$( grep -E "$hiveon_freq_and_voltage_RE" "$source_file" | sort )" && [[ -n "$fv_settings_from_source_config" ]]; then
+					(( script_DEBUG )) && echo "  [DEBUG] getting freq/voltage settings from $source_file..."
+					if non_fv_settings_from_destination_config="$( grep -v -E "$hiveon_freq_and_voltage_RE" "$destination_file" )" && [[ -n "$non_fv_settings_from_destination_config" ]]; then
+						cp -p "$destination_file" "$destination_file.previous" # for emergencies
+						(( script_DEBUG )) && echo "  [DEBUG] pasting freq/voltage settings to $destination_file..."
+						printf '%s\n%s\n' "$fv_settings_from_source_config" "$non_fv_settings_from_destination_config" > "$destination_file"
+					else
+						(( script_DEBUG )) && echo "  [DEBUG] there are no any settings in $destination_file. Weird, eh..."
+					fi
+				else
+					(( script_DEBUG )) && echo "  [DEBUG] there are no freq/voltage settings in $source_file. Weird, eh..."
+				fi
+			else
+				# cp -p: preserve timestamp
+				if cp -pf "$source_file" "$destination_file"; then
+					(( script_DEBUG )) && echo "  [DEBUG] copying $source_file to $active_profile_directory/..."
+					is_something_restored_FLAG=1
+				fi
 			fi
 		else
 			# if source is not exist, but destination is -- delete destination then
@@ -488,7 +506,7 @@ function restore_cached_profile {
 	return $(( is_something_restored_FLAG ))
 }
 
-function deactivate_active_profile_files {
+function deactivate_active_files {
 	# args
 	(( $# > 0 )) || return 1
 
@@ -501,11 +519,27 @@ function deactivate_active_profile_files {
 		this_file_w_path="$active_profile_directory/$this_file"
 		echo -n "  [DEBUG] $this_file_w_path "
 		if [[ -f "$this_file_w_path" ]]; then
-			mv -f "$this_file_w_path" "$this_file_w_path.previous" && echo 'OK (renamed to *.previous)' || echo 'FAIL (rename error)'
+			if [[ "$this_file" == "$hiveon_config_file" ]]; then
+				# some sort of a kludge for L3+ Hiveon 1.02 (and the others, maybe)
+				# leave an original config.conf because it's crucial to leave it be
+				cp "$this_file_w_path" "$this_file_w_path.previous" && echo 'OK (copied to *.previous)' || echo 'FAIL (copy error)'
+			else
+				mv -f "$this_file_w_path" "$this_file_w_path.previous" && echo 'OK (renamed to *.previous)' || echo 'FAIL (rename error)'
+			fi
 		else
 			echo 'SKIPPED (not exist)'
 		fi
 	done
+}
+
+function deactivate_active_profile_files {
+	# wrapper
+	deactivate_active_files "${profile_files_collection[@]}"
+}
+
+function deactivate_active_tune_files {
+	# wrapper
+	deactivate_active_files "${tune_files_collection[@]}"
 }
 
 
@@ -676,7 +710,7 @@ function kill_autotune_9 {
 	local -i kill_counter
 
 	# code
-	(( script_DEBUG )) && echo '> [DEBUG] Stopping auto-tune tools...'
+	(( script_DEBUG )) && echo '> [DEBUG] Stopping all auto-tune processes...'
 	for this_process in 'auto-tune' 'tune-yellow' 'auto-chip-tune' 'auto-tune-chains'; do
 		kill_counter=0
 		while is_process_running "$this_process"; do
@@ -695,7 +729,8 @@ function generate_active_profile_9 {
 	echo '> Generating active profile for Series 9...'
 	# build a fresh config file for auto-tune
 	(( script_DEBUG )) && { echo "[DEBUG] incoming profile as key=value: [$incoming_profile_as_key_value_pairs]"; echo; }
-	printf '%s' "$incoming_profile_as_key_value_pairs" | replace_newlines_with_ampersands > "$active_profile_file_w_path"
+	printf '%s' "$incoming_profile_as_key_value_pairs" |
+		replace_newlines_with_ampersands > "$active_profile_file_w_path"
 	(( script_DEBUG )) && { echo "[DEBUG] generated file: [$( cat "$active_profile_file_w_path" )]"; echo; }
 }
 
@@ -747,8 +782,8 @@ function tune_9 {
 	echo '> 1st phase finished'
 
 	if (( script_DEBUG )); then
-		if [[ ! -f "$active_profile_directory/config.conf" ]]; then
-			echo "  [DEBUG] $active_profile_directory/config.conf not found (but it has to be)" # ??? do we still need this
+		if [[ ! -f "$active_hiveon_config_file" ]]; then
+			echo "  [DEBUG] $active_hiveon_config_file not found (but it has to be)" # ??? do we still need this
 		fi
 		if [[ -f "$autotune_debug_log" ]]; then
 			echo '> [DEBUG] Auto-tune log:'
@@ -783,24 +818,22 @@ function tune_9 {
 
 function fix_autotune_bugs_9 {
 	#
-	# fix 1: remove all empty lines from config.conf
-	# fix 2: delete config.conf if empty
+	# fixes for $active_hiveon_config_file:
+	# 1. remove all empty lines
+	# 2. delete if empty
 	#
-
-	# consts
-	local -r hiveon_config_file="$active_profile_directory/config.conf"
 
 	# code
 	# shellcheck disable=SC2154
 	# ...bc defined in the library
-	if is_file_exist_and_contain "$hiveon_config_file" "$empty_line_RE"; then
-		(( script_DEBUG )) && echo "  [DEBUG] $hiveon_config_file contains empty lines, deleting them"
-		sed -i "/$empty_line_RE/d" "$hiveon_config_file" # > /dev/null 2>&1
+	if is_file_exist_and_contain "$active_hiveon_config_file" "$empty_line_RE"; then
+		(( script_DEBUG )) && echo "  [DEBUG] $active_hiveon_config_file contains empty lines, deleting them"
+		sed -i "/$empty_line_RE/d" "$active_hiveon_config_file" # > /dev/null 2>&1
 	fi
 
-	if is_file_exist_but_empty "$hiveon_config_file"; then
-		(( script_DEBUG )) && echo "  [DEBUG] Empty $hiveon_config_file, removing the file"
-		rm "$hiveon_config_file"
+	if is_file_exist_but_empty "$active_hiveon_config_file"; then
+		(( script_DEBUG )) && echo "  [DEBUG] Empty $active_hiveon_config_file, removing the file"
+		rm "$active_hiveon_config_file"
 	fi
 }
 
@@ -862,8 +895,8 @@ function tune_L3 {
 	fi
 
 	if (( script_DEBUG )); then
-		if [[ ! -f "$active_profile_directory/config.conf" ]]; then
-			echo "  [DEBUG] $active_profile_directory/config.conf not found (but it has to be)" # ??? do we still need this
+		if [[ ! -f "$active_hiveon_config_file" ]]; then
+			echo "  [DEBUG] $active_hiveon_config_file not found (but it has to be)" # ??? do we still need this
 		fi
 		if [[ -f "$autotune_debug_log" ]]; then
 			echo '> [DEBUG] Auto-tune log:'
@@ -1080,12 +1113,15 @@ source /hive/bin/hive-functions.sh	|| die '/hive/bin/hive-functions.sh not found
 declare -r active_profile_directory='/config'
 declare -r cached_profiles_directory='/config/profiles'
 
+declare -r hiveon_config_file='config.conf'
+declare -r active_hiveon_config_file="$active_profile_directory/$hiveon_config_file"
+
 declare -r ant17_profile_filename="profile.txt"
-declare -r -a ant17_tune_files_collection=( 'manual_freqs.txt' )
+declare -r -a ant17_tune_files_collection=( 'manual_freqs.txt' "$hiveon_config_file" )
 declare -r -a ant17_profile_files_collection=( "$ant17_profile_filename" "${ant17_tune_files_collection[@]}" )
 
 declare -r ant9_profile_filename="autoTune.conf"
-declare -r -a ant9_tune_files_collection=( 'manual_freqs.txt' 'yellow-step' )
+declare -r -a ant9_tune_files_collection=( 'manual_freqs.txt' 'yellow-step' "$hiveon_config_file" )
 declare -r -a ant9_profile_files_collection=( "$ant9_profile_filename" "${ant9_tune_files_collection[@]}" )
 
 
@@ -1147,16 +1183,17 @@ case "$oc_action" in
 	"$oc_action_FACTORY")
 		echo '<h3>Setting profile to factory defaults</h3>'
 		if [[ -s "$active_profile_file_w_path" ]]; then
-			message_text="$active_profile_description is OFF. Running on non-optimal factory settings"
+			message_text="$active_profile_description is OFF. Now running with sub-optimal factory settings"
 			#
 			have_to_restart_miner_FLAG=1
 		else
-			message_text='Already running on non-optimal factory settings'
+			message_text='Already running on sub-optimal factory settings'
 			#
 			have_to_restart_miner_FLAG=0
 		fi
 		echo "$message_text"
-		deactivate_active_profile_files "${profile_files_collection[@]}" | tee >( message warning "$message_text" payload > /dev/null )
+		deactivate_active_profile_files |
+			tee >( message 'warning' "$message_text" --payload > /dev/null )
 		#
 		have_to_generate_active_profile_FLAG=0
 		have_to_tune_FLAG=0
@@ -1181,7 +1218,8 @@ case "$oc_action" in
 		fi
 		echo "$message_text"
 		echo
-		deactivate_active_profile_files "${tune_files_collection[@]}" | tee >( message "$message_event_type" "$message_text" > /dev/null )
+		deactivate_active_tune_files |
+			tee >( message "$message_event_type" "$message_text" --payload > /dev/null )
 		#
 		have_to_generate_active_profile_FLAG=0
 	;;
@@ -1241,7 +1279,7 @@ case "$oc_action" in
 					# does cached profile ID not equal to incoming profile ID?
 					# ...does NOT equal. copy cached profile over the active one
 					echo "> Cached profile #$incoming_profile_id found. It's equal to incoming. Using cached one."
-					message info "$message_text. Cached profile activated, auto-tuning skipped" > /dev/null
+					message 'info' "$message_text. Cached profile activated, auto-tuning skipped" > /dev/null
 
 					restore_cached_profile "$incoming_profile_id"
 
@@ -1250,7 +1288,7 @@ case "$oc_action" in
 						have_to_tune_FLAG=0
 					else
 						echo "> Chip tuning file (manual_freqs.txt) is missing. Profile has to be tuned."
-						message warning 'Cached profile is not fully tuned and has to be tuned again' > /dev/null
+						message 'warning' 'Cached profile is not fully tuned. Engaging auto-tune...' > /dev/null
 						#
 						have_to_tune_FLAG=1
 					fi
@@ -1262,7 +1300,7 @@ case "$oc_action" in
 					# does cached profile ID not equal to incoming profile ID?
 					# ...yes it does, the same ID! do nothing.
 					echo "> Cached and incoming profiles are equal and have the same ID. Nothing to do."
-					message warning "$message_text. Profiles are the same, any actions skipped" > /dev/null
+					message 'warning' "$message_text. Profiles are the same, any actions skipped" > /dev/null
 					#
 					have_to_generate_active_profile_FLAG=0
 					have_to_restart_miner_FLAG=0
@@ -1274,7 +1312,7 @@ case "$oc_action" in
 				echo "> Cached profile #$incoming_profile_id found. It ISN'T equal to incoming profile. Using incoming one."
 				print_differencies_in_profiles |
 					tee >(
-						message warning "$message_text. Cached profile is outdated, click for details. Profile has updated and needs to be tuned" payload > /dev/null
+						message 'warning' "$message_text. Cached profile is outdated. Engaging auto-tune..." --payload > /dev/null
 					)
 				#
 				have_to_generate_active_profile_FLAG=1
@@ -1285,16 +1323,19 @@ case "$oc_action" in
 			# does cached profile exist (and isn't empty)?
 			# ...no, cached profile does not exist (or --force argument is in use). let's generate a brand new profile.
 			if (( forced_apply_incoming_profile_FLAG )); then
-				message info "$message_text. Forced apply, ignoring cached data" > /dev/null
+				message 'info' "$message_text. Forced apply, ignoring cached data" > /dev/null
 			else
-				message info "$message_text" > /dev/null
+				message 'info' "$message_text" > /dev/null
 			fi
 			#
 			have_to_generate_active_profile_FLAG=1
 			have_to_restart_miner_FLAG=1
 			have_to_tune_FLAG=1
 		fi
-		(( have_to_generate_active_profile_FLAG )) && deactivate_active_profile_files "${profile_files_collection[@]}"
+
+		if (( have_to_generate_active_profile_FLAG )); then
+			deactivate_active_profile_files
+		fi
 	;;
 
 	*)
@@ -1308,9 +1349,7 @@ esac
 # proceed model-dependent actions
 #
 
-# shellcheck disable=SC2076
 if [[ ( "$ASIC_MODEL" == 'Antminer S9'* || "$ASIC_MODEL" == 'Antminer T9'* ) && ( "$ASIC_CUSTOM_FW_VERSION" == '1.02' || "$ASIC_CUSTOM_FW_VERSION" == '1.03' ) ]]; then
-# ...bc we need a literal match
 
 	if (( have_to_generate_active_profile_FLAG )); then
 		generate_active_profile_9
