UPDATE asic-oc
* added fix_tune_files_ownership()

diff --git a/hive/bin/asic-oc b/hive/bin/asic-oc
--- a/hive/bin/asic-oc
+++ b/hive/bin/asic-oc
@@ -11,7 +11,7 @@
 
 
 readonly script_mission='Client for ASICs: Antminer overclock profiles management'
-readonly script_version='0.5.35'
+readonly script_version='0.5.36'
 readonly script_basename="$( basename "$0" )"
 readonly script_DEBUG=1
 
@@ -675,6 +675,36 @@ function print_differencies_in_profiles {
 
 # auxillary
 
+function fix_tune_files_ownership {
+	#
+	# fix tune files ownership for CGI scripts
+	#
+
+	# args
+	(( $# == 0 )) || return 1
+
+	# vars
+	local lighttpd_owner this_file
+
+	# code
+	lighttpd_owner="$( ps | awk '/lighttpd/ && !/awk/ {print $2}' )"
+	if [[ -n "$lighttpd_owner" && "$lighttpd_owner" != 'root' ]]; then
+		echo "> Fixing profile ownership for '$lighttpd_owner'..."
+		for this_file in "${profile_files_collection[@]}"; do
+			(( script_DEBUG )) && echo -n "  [DEBUG] $this_file "
+			if [[ -f "$active_profile_directory/$this_file" ]]; then
+				if chown "$lighttpd_owner:$lighttpd_owner" "$active_profile_directory/$this_file" > /dev/null 2>&1; then
+					(( script_DEBUG )) && echo 'OK'
+				else
+					(( script_DEBUG )) && echo 'FAIL'
+				fi
+			else
+				(( script_DEBUG )) && echo 'OK (not exist)'
+			fi
+		done
+	fi
+}
+
 function replace_newlines_with_ampersands {
 	# args
 	(( $# == 0 )) || return 1
@@ -928,23 +958,7 @@ if [[ $HIVEON_VERSION == '1.02' || $HIVEON_VERSION == '1.03' ]] && [[ $ASIC_MODE
 	fi
 
 	if (( have_to_generate_active_profile_FLAG || have_to_restart_miner_FLAG || have_to_tune_FLAG )); then
-		# fix tune files ownership (for CGI scripts)
-		lighttpd_owner="$( ps | awk '/lighttpd/ && !/awk/ {print $2}' )"
-		if [[ -n "$lighttpd_owner" && "$lighttpd_owner" != 'root' ]]; then
-			echo "> Fixing profile ownership for '$lighttpd_owner'..."
-			for this_file in "${profile_files_collection[@]}"; do
-				(( script_DEBUG )) && echo -n "  [DEBUG] $this_file "
-				if [[ -f "$active_profile_directory/$this_file" ]]; then
-					if chown "$lighttpd_owner:$lighttpd_owner" "$active_profile_directory/$this_file" > /dev/null 2>&1; then
-						(( script_DEBUG )) && echo 'OK'
-					else
-						(( script_DEBUG )) && echo 'FAIL'
-					fi
-				else
-					(( script_DEBUG )) && echo 'OK (not exist)'
-				fi
-			done
-		fi
+		fix_tune_files_ownership
 	fi
 
 	if (( have_to_restart_miner_FLAG )); then
@@ -1126,23 +1140,7 @@ else
 	fi
 
 	if (( have_to_generate_active_profile_FLAG || have_to_restart_miner_FLAG || have_to_tune_FLAG )); then
-		# fix tune files ownership (for CGI scripts)
-		lighttpd_owner="$( ps | awk '/lighttpd/ && !/awk/ {print $2}' )"
-		if [[ -n "$lighttpd_owner" && "$lighttpd_owner" != 'root' ]]; then
-			echo "> Fixing profile ownership for '$lighttpd_owner'..."
-			for this_file in "${profile_files_collection[@]}"; do
-				(( script_DEBUG )) && echo -n "  [DEBUG] $this_file "
-				if [[ -f "$active_profile_directory/$this_file" ]]; then
-					if chown "$lighttpd_owner:$lighttpd_owner" "$active_profile_directory/$this_file" > /dev/null 2>&1; then
-						(( script_DEBUG )) && echo 'OK'
-					else
-						(( script_DEBUG )) && echo 'FAIL'
-					fi
-				else
-					(( script_DEBUG )) && echo 'OK (not exist)'
-				fi
-			done
-		fi
+		fix_tune_files_ownership
 	fi
 
 	if (( have_to_restart_miner_FLAG )); then
