UPDATE asic-oc
* removed config.conf from the profile's scope
* improved fix_autotune_bugs_9()
* added generate_active_profile_L3()
* added a separate L3+ 1.02/1.03 handler

diff --git a/hive/bin/asic-oc b/hive/bin/asic-oc
--- a/hive/bin/asic-oc
+++ b/hive/bin/asic-oc
@@ -11,7 +11,7 @@
 
 
 readonly script_mission='Client for ASICs: Antminer overclock profiles management'
-readonly script_version='0.6.29'
+readonly script_version='0.6.30'
 readonly script_basename="${0##*/}"
 #
 readonly script_DEBUG="${script_DEBUG:-1}" # use value from env if exists
@@ -501,13 +501,7 @@ function deactivate_active_profile_files {
 		this_file_w_path="$active_profile_directory/$this_file"
 		echo -n "  [DEBUG] $this_file_w_path "
 		if [[ -f "$this_file_w_path" ]]; then
-			if [[ "$this_file" == 'config.conf' ]]; then
-				# some sort of a kludge for L3+ Hiveon 1.02
-				# leave an original config.conf because it's crucial to leave it be
-				cp "$this_file_w_path" "$this_file_w_path.previous" && echo 'OK (copied to *.previous)' || echo 'FAIL (copy error)'
-			else
-				mv -f "$this_file_w_path" "$this_file_w_path.previous" && echo 'OK (renamed to *.previous)' || echo 'FAIL (rename error)'
-			fi
+			mv -f "$this_file_w_path" "$this_file_w_path.previous" && echo 'OK (renamed to *.previous)' || echo 'FAIL (rename error)'
 		else
 			echo 'SKIPPED (not exist)'
 		fi
@@ -670,7 +664,7 @@ function print_differencies_in_profiles {
 # model-dependent tune & restart
 #
 
-# Series 9 (and the others)
+# Antminer Series 9 (and the others)
 
 function kill_autotune_9 {
 	#
@@ -698,7 +692,7 @@ function kill_autotune_9 {
 }
 
 function generate_active_profile_9 {
-	echo '> Generating active profile...'
+	echo '> Generating active profile for Series 9...'
 	# build a fresh config file for auto-tune
 	(( script_DEBUG )) && { echo "[DEBUG] incoming profile: [$incoming_profile]"; echo; }
 	printf '%s' "$incoming_profile" | replace_newlines_with_ampersands > "$active_profile_file_w_path"
@@ -745,7 +739,7 @@ function tune_9 {
 
 	if (( script_DEBUG )); then
 		if [[ ! -f "$active_profile_directory/config.conf" ]]; then
-			echo "  [DEBUG] $active_profile_directory/config.conf not found (but it have to be)"
+			echo "  [DEBUG] $active_profile_directory/config.conf not found (but it has to be)" # ??? do we still need this
 		fi
 		if [[ -f "$autotune_debug_log" ]]; then
 			echo '> [DEBUG] Auto-tune log:'
@@ -780,8 +774,8 @@ function tune_9 {
 
 function fix_autotune_bugs_9 {
 	#
-	# fix autotune bug for S9/L3/etc: if config exists, but its size is zero -> delete it
-	# fix config.conf: remove all empty lines
+	# fix 1: remove all empty lines from config.conf
+	# fix 2: delete empty config.conf
 	#
 
 	# consts
@@ -789,19 +783,46 @@ function fix_autotune_bugs_9 {
 	local -r empty_line_RE='^[[:space:]]*$'
 
 	# code
-	if is_file_exist_but_empty "$hiveon_config_file"; then
-		(( script_DEBUG )) && echo "  [DEBUG] Empty $hiveon_config_file, removing the file"
-		rm "$hiveon_config_file"
-	elif is_file_exist_and_contain "$hiveon_config_file" "$empty_line_RE"; then
+	if is_file_exist_and_contain "$hiveon_config_file" "$empty_line_RE"; then
 		(( script_DEBUG )) && echo "  [DEBUG] $hiveon_config_file contains empty lines, deleting them"
 		sed "|$empty_line_RE|d" -i "$hiveon_config_file" # > /dev/null 2>&1
 	fi
+
+	if is_file_exist_but_empty "$hiveon_config_file"; then
+		(( script_DEBUG )) && echo "  [DEBUG] Empty $hiveon_config_file, removing the file"
+		rm "$hiveon_config_file"
+	fi
 }
 
-# Series 17
+# Antminer L3+/L3++
+
+function generate_active_profile_L3 {
+	echo '> Generating active profile for L3+/L3++...'
+	# build a fresh config file for auto-tune
+	(( script_DEBUG )) && { echo "[DEBUG] incoming profile: [$incoming_profile]"; echo; }
+	{
+		printf '%s' "$incoming_profile"
+		if ! grep -Eq -e '^hw_per_minute_avg_threshold=[0-9]+$' <<< "$incoming_profile"; then
+			# a kind of rude temporary fix:
+			printf '\n'
+			printf '%s\n'	'hw_per_minute_avg_threshold=20'
+			printf '%s\n'	'wait_after_restart=100'
+			printf '%s\n'	'wait_test_run_seconds=360'
+			printf '%s\n'	'stat_poll_interval=30'
+			printf '%s\n'	'hw_freq_step=4'
+			printf '%s\n'	'hw_threshold_value=5'
+			printf '%s\n'	'max_restarts=15'
+			printf '%s\n'	'hw_wait_on_start=180'
+			printf '%s'		'total_hw_rate_threshold=0.1'
+		fi
+	} | replace_newlines_with_ampersands > "$active_profile_file_w_path"
+	(( script_DEBUG )) && { echo "[DEBUG] generated file: [$( cat "$active_profile_file_w_path" )]"; echo; }
+}
+
+# Antminer Series 17
 
 function generate_active_profile_17 {
-	echo '> Generating active profile...'
+	echo '> Generating active profile for Series 17...'
 	# build a fresh config file for auto-tune
 	{
 		if ! grep -Eq -e '^tune_profile=[0-9]+$' <<< "$incoming_profile"; then
@@ -995,7 +1016,7 @@ declare -r -a ant17_tune_files_collection=( 'manual_freqs.txt' )
 declare -r -a ant17_profile_files_collection=( "$ant17_profile_filename" "${ant17_tune_files_collection[@]}" )
 
 declare -r ant9_profile_filename="autoTune.conf"
-declare -r -a ant9_tune_files_collection=( 'manual_freqs.txt' 'yellow-step' 'config.conf' )
+declare -r -a ant9_tune_files_collection=( 'manual_freqs.txt' 'yellow-step' )
 declare -r -a ant9_profile_files_collection=( "$ant9_profile_filename" "${ant9_tune_files_collection[@]}" )
 
 
@@ -1218,7 +1239,7 @@ esac
 #
 
 # shellcheck disable=SC2076
-if [[ ( "$ASIC_CUSTOM_FW_VERSION" == '1.02' || "$ASIC_CUSTOM_FW_VERSION" == '1.03' ) && ( "$ASIC_MODEL" == 'Antminer S9'* || "$ASIC_MODEL" == 'Antminer T9'* ) ]]; then
+if [[ ( "$ASIC_MODEL" == 'Antminer S9'* || "$ASIC_MODEL" == 'Antminer T9'* ) && ( "$ASIC_CUSTOM_FW_VERSION" == '1.02' || "$ASIC_CUSTOM_FW_VERSION" == '1.03' ) ]]; then
 # ...bc we need a literal match
 
 	if (( have_to_generate_active_profile_FLAG )); then
@@ -1241,7 +1262,23 @@ if [[ ( "$ASIC_CUSTOM_FW_VERSION" == '1.02' || "$ASIC_CUSTOM_FW_VERSION" == '1.0
 		tune_9
 	fi
 
-elif [[ "$ASIC_CUSTOM_FW_VERSION" == '1.00' && ( "$ASIC_MODEL" == "Antminer S17 $ASIC_CUSTOM_FW_BRAND"* || "$ASIC_MODEL" == "Antminer T17 $ASIC_CUSTOM_FW_BRAND"* ) ]]; then
+elif [[ "$ASIC_MODEL" == 'Antminer L3+'* && ( "$ASIC_CUSTOM_FW_VERSION" == '1.02' || "$ASIC_CUSTOM_FW_VERSION" == '1.03' ) ]]; then
+
+	if (( have_to_generate_active_profile_FLAG )); then
+		generate_active_profile_L3
+	fi
+
+	fix_autotune_bugs_9
+
+	if (( have_to_restart_miner_FLAG )); then
+		restart_miner_9
+	fi
+
+	if (( have_to_tune_FLAG )); then
+		tune_9
+	fi
+
+elif [[ ( "$ASIC_MODEL" == "Antminer S17 $ASIC_CUSTOM_FW_BRAND"* || "$ASIC_MODEL" == "Antminer T17 $ASIC_CUSTOM_FW_BRAND"* ) && "$ASIC_CUSTOM_FW_VERSION" == '1.00' ]]; then
 
 	if (( have_to_generate_active_profile_FLAG )); then
 		generate_active_profile_17
