UPDATE hive-functions.sh, asic-oc, miner
hive-functions.sh:
* documented a bit
* renamed is_program_...() to is_process_...()
* added get_process_owner()

asic-oc:
* renamed is_program_...() to is_process_...()
* improved restart_miner_9()
* simplified get_lighttpd_owner() as wrapper for get_process_owner()

miner:
* improved miner_stop() to take an lighttpd_owner into account

diff --git a/hive/bin/asic-oc b/hive/bin/asic-oc
--- a/hive/bin/asic-oc
+++ b/hive/bin/asic-oc
@@ -11,7 +11,7 @@
 
 
 readonly script_mission='Client for ASICs: Antminer overclock profiles management'
-readonly script_version='0.6.38'
+readonly script_version='0.6.39'
 readonly script_basename="${0##*/}"
 #
 readonly script_DEBUG="${script_DEBUG:-1}" # use value from env if exists
@@ -679,7 +679,7 @@ function kill_autotune_9 {
 	(( script_DEBUG )) && echo '> [DEBUG] Stopping auto-tune tools...'
 	for this_process in 'auto-tune' 'tune-yellow' 'auto-chip-tune' 'auto-tune-chains'; do
 		kill_counter=0
-		while is_program_running "$this_process"; do
+		while is_process_running "$this_process"; do
 			if (( ++kill_counter > 10 )); then
 				(( script_DEBUG )) && echo "  [DEBUG] $this_process is still alive after $kill_counter tries!"
 				break
@@ -700,19 +700,26 @@ function generate_active_profile_9 {
 }
 
 function restart_miner_9 {
+	# consts
+	local -r restart_miner_FILE="$active_profile_directory/restart"
+	local -r restart_miner_command='ok'
+
 	# code
 	kill_autotune_9
 	echo '> Restarting miner...'
-	# shellcheck disable=SC2076
-	if [[ "$ASIC_MODEL" =~ 'Antminer L3' ]]; then
-	# ...bc we need a literal match
+
+	if [[ "$ASIC_MODEL" == 'Antminer L3'* ]]; then
 		killall -9 cgminer
+		return
+	fi
+
+	if ! echo "$restart_miner_command" > "$restart_miner_FILE"; then
+		echo "  [ERROR] couldn't create $restart_miner_FILE"
 	else
 		if (( is_lighttpd_not_running_as_root_FLAG )); then
-			# create file as lighttpd owner
-			su - "$lighttpd_owner" -c "echo 'ok' > $active_profile_directory/restart" > /dev/null 2>&1
-		else
-			echo 'ok' > "$active_profile_directory/restart"
+			if ! chown "$lighttpd_owner:$lighttpd_owner" "$restart_miner_FILE" > /dev/null 2>&1; then
+				echo "  [ERROR] couldn't chown $restart_miner_FILE as '$lighttpd_owner'"
+			fi
 		fi
 	fi
 }
@@ -969,11 +976,7 @@ function tune_17_new {
 
 function get_lighttpd_owner {
 	# code
-	if is_program_running 'lighttpd'; then
-		ps | awk '/lighttpd/ && !/awk/ {print $2}'
-	else
-		return $(( exitcode_ERROR_NOT_FOUND ))
-	fi
+	get_process_owner 'lighttpd'
 }
 
 function is_lighttpd_not_running_as_root {
@@ -1338,7 +1341,10 @@ elif [[ "$ASIC_MODEL" == 'Antminer L3+'* && ( "$ASIC_CUSTOM_FW_VERSION" == '1.02
 	fix_autotune_bugs_9
 
 	if (( have_to_restart_miner_FLAG )); then
-		restart_miner_9
+		if [[ "$ASIC_CUSTOM_FW_VERSION" != '1.03' ]]; then
+			# in 1.03 we don't have to kill the miner
+			restart_miner_9
+		fi
 	fi
 
 	if (( have_to_tune_FLAG )); then
diff --git a/hive/bin/miner b/hive/bin/miner
--- a/hive/bin/miner
+++ b/hive/bin/miner
@@ -13,7 +13,7 @@
 # shellcheck disable=SC2034,SC1091
 {
 	readonly script_mission='Client for ASICs: Miner controller'
-	readonly script_version='1.3.8'
+	readonly script_version='1.3.9'
 	readonly script_basename="${0##*/}"
 	#
 	source /hive/bin/hive-functions.sh || { echo 'ERROR: /hive/bin/hive-functions.sh not found'; exit 1; }
@@ -184,6 +184,11 @@ function miner_stop {
 	if [[ -f /sbin/watchdog_restart.pl ]]; then
 		# S9/T9 Hiveon
 		echo 'ok' > /tmp/norespawn
+		if lighttpd_owner="$( get_process_owner 'lighttpd' )" && [[ "$lighttpd_owner" != 'root' ]]; then
+			if ! chown "$lighttpd_owner:$lighttpd_owner" /tmp/norespawn > /dev/null 2>&1; then
+				echo_x error "Couldn't chown /tmp/norespawn as '$lighttpd_owner'"
+			fi
+		fi
 	elif [[ -f /www/pages/cgi-bin/stop_miner.cgi ]]; then
 		# S17/T17 Hiveon
 		sh /www/pages/cgi-bin/stop_miner.cgi
