UPDATE controller
* disabled a warning message in checkup:is_there_JFFS2_error() -- to ease the users' anxiety
* moved RIG_CONF definition to the global consts section
* linted, bag and baggage

diff --git a/hive/bin/controller b/hive/bin/controller
--- a/hive/bin/controller
+++ b/hive/bin/controller
@@ -6,13 +6,13 @@
 # Distributed under Business Source License 1.1
 # License information can be found in the LICENSE.txt file or at https://github.com/minershive/hiveos-asic/blob/master/LICENSE.txt
 #
-# Linted by shellcheck 0.7.0
+# Linted by shellcheck 0.7.0 (100%)
 #
 
 
 # shellcheck disable=SC2034
 readonly script_mission='Client for ASICs: Routine controller'
-readonly script_version='2.4.5'
+readonly script_version='2.4.6'
 readonly script_basename="${0##*/}"
 #
 readonly script_DEBUG="${script_DEBUG:-0}" # use value from env if exists
@@ -1147,7 +1147,9 @@ function sync_time_via_hive_server { # not used atm
 
 	# code
 
-	HIVE_HOST_URL="$( [[ -s /hive-config/rig.conf ]] && source /hive-config/rig.conf && echo "${HIVE_HOST_URL-}" )"
+	# shellcheck disable=SC1090
+	# just because
+	HIVE_HOST_URL="$( [[ -s "$RIG_CONF" ]] && source "$RIG_CONF" && echo "${HIVE_HOST_URL-}" )"
 
 	if [[ -z ${HIVE_HOST_URL-} ]]; then
 		HIVE_HOST_URL='http://api.hiveos.farm'
@@ -1203,7 +1205,9 @@ function checkup:is_it_the_past {																	(( script_DEBUG )) && debugcho
 	if (( current_year < 2021 )); then
 		is_something_happened=$(( exitcode_WARNING_SOMETHING_HAPPENED ))
 
-		HIVE_HOST_URL="$( [[ -s /hive-config/rig.conf ]] && source /hive-config/rig.conf && echo "${HIVE_HOST_URL-}" )"
+		# shellcheck disable=SC1090
+		# just because
+		HIVE_HOST_URL="$( [[ -s "$RIG_CONF" ]] && source "$RIG_CONF" && echo "${HIVE_HOST_URL-}" )"
 
 		if [[ -z ${HIVE_HOST_URL-} ]]; then
 			HIVE_HOST_URL='http://api.hiveos.farm'
@@ -1368,8 +1372,6 @@ function checkup:is_custom_fw_config_in_sync {														(( script_DEBUG )) &
 
 	# consts
 
-	local -r RIG_CONF_default='/hive-config/rig.conf'
-	local -r RIG_CONF="${RIG_CONF:-$RIG_CONF_default}" # for ASIC emulator: set to default only if RIG_CONF variable is empty
 	local -r HIVEON_CONF='/hive-config/hiveon.conf'
 	local -r ASIC_CONF='/config/config.conf'
 
@@ -1396,6 +1398,8 @@ function checkup:is_custom_fw_config_in_sync {														(( script_DEBUG )) &
 
 	if (( ! is_RIG_ID_ok_FLAG )); then
 		# check RIG_ID
+		# shellcheck disable=SC1090
+		# just because
 		if [[ -s "$RIG_CONF" ]] && ( source "$RIG_CONF"; [[ -n "$RIG_ID" ]] ); then
 			is_RIG_ID_ok_FLAG=1
 		fi
@@ -1692,7 +1696,7 @@ function checkup:is_there_JFFS2_error {																(( script_DEBUG )) && deb
 	# templates
 
 	local -r event_type_for_log='warning'			# error|warning|info
-	local -r event_type_for_message='warning'		# error|warning|info|success
+	local -r event_type_for_message='SKIP'			# error|warning|info|success|SKIP
 	local -r message_header='NAND flash error detected. Click for technical details'
 
 	# consts
@@ -1711,7 +1715,9 @@ function checkup:is_there_JFFS2_error {																(( script_DEBUG )) && deb
 		if jffs2_errors_list="$( dmesg | grep -Ei "$jffs2_errors_RE" )" && [[ -n "$jffs2_errors_list" ]]; then
 			printf -v message_body "Mining is not affected (most likely). It could be in connection with an unclean reboot OR, rarely, with a NAND wear and tear. The first is completely harmless, but the second does suggest that the ASIC's control board may need a service or replacement in the very near future.\n\nErrors:\n\n%s" "$jffs2_errors_list"
 			print_controller_log_entry "$event_type_for_log" "$message_header"
-			message "$event_type_for_message" "$message_header" --silent --payload <<< "$message_body"
+			if [[ "$event_type_for_message" != 'SKIP' ]]; then
+				message "$event_type_for_message" "$message_header" --silent --payload <<< "$message_body"
+			fi
 			set_checkup_counter "${FUNCNAME[0]}" 'message_sent' 1
 			is_something_happened=$(( exitcode_WARNING_SOMETHING_HAPPENED ))
 		fi
@@ -2129,7 +2135,10 @@ function do_cron_jobs_indefinitely {																(( script_DEBUG )) && debugc
 
 # global consts
 
-declare -r -i assign_tag_to_worker=1 # can be in config file
+declare -r RIG_CONF_default='/hive-config/rig.conf'
+declare -r RIG_CONF="${RIG_CONF:-$RIG_CONF_default}" # for ASIC emulator: set to default only if RIG_CONF variable is empty
+
+declare -r -i assign_tag_to_worker=1 # could be in a config file?
 declare -r -i log_lines_to_tail=200
 declare -r unique_delimiter="d${RANDOM}e${RANDOM}l${RANDOM}i${RANDOM}m"
 
@@ -2141,9 +2150,13 @@ declare -r ntp_server='pool.ntp.org'
 
 # global sources
 
-source /hive/bin/asic-model			|| echo 'ERROR: /hive/bin/asic-model not found'
-source /hive/bin/colors				|| echo 'ERROR: /hive/bin/colors not found'
-source /hive/bin/hive-functions.sh	|| { echo 'ERROR: /hive/bin/hive-functions.sh not found'; exit 1; }
+# shellcheck disable=SC1091
+# just because
+{
+	source /hive/bin/asic-model				|| echo 'ERROR: /hive/bin/asic-model not found'
+	source /hive/bin/colors					|| echo 'ERROR: /hive/bin/colors not found'
+	source /hive/bin/hive-functions.sh		|| { echo 'ERROR: /hive/bin/hive-functions.sh not found'; exit 1; }
+}
 
 
 # global exports
