UPDATE hello
* added API server sanity check -- now the hello doesn't try to connect to the non-Hive server

diff --git a/hive/bin/hello b/hive/bin/hello
--- a/hive/bin/hello
+++ b/hive/bin/hello
@@ -17,7 +17,7 @@
 
 # Sends hello to Hive, receives config files, restarts miner
 readonly script_mission='Client for ASICs: Say hello to the server'
-readonly script_version='0.1.13'
+readonly script_version='0.1.14'
 readonly script_basename="$( basename "$0" )"
 readonly script_debug=0
 
@@ -133,11 +133,18 @@ function print_JSON_with_header {
 	local expected_JSON="$2"
 
 	# vars
-	local checked_JSON entity_to_print
+	local checked_JSON entity_to_print color_option
 	local -i entity_size
 
 	# code
-	if checked_JSON="$( jq --compact-output '.' <<< "$expected_JSON" 2> /dev/null )"; then
+	if [[ -z "${FARM_HASH-}" ]]; then
+		color_option='--color-output'
+	else
+		# turn the colors off for cgi-bin script
+		color_option='--monochrome-output'
+	fi
+
+	if checked_JSON="$( jq --compact-output "$color_option" '.' <<< "$expected_JSON" 2> /dev/null )"; then
 		entity_type='JSON'
 		entity_to_print="$checked_JSON"
 	else
@@ -146,7 +153,7 @@ function print_JSON_with_header {
 	fi
 
 	entity_size="${#entity_to_print}"
-	echo -e "${LGRAY}${script_basename}:${NOCOLOR} $header ($entity_type $entity_size bytes)"
+	echo -e "${LGRAY}${script_basename}:${NOCOLOR} $header ($entity_type $entity_size bytes):"
 	echo "$entity_to_print"
 }
 
@@ -422,14 +429,22 @@ function serve_hiveon_model_cache {
 function send_hello_packet {
 	# try to send the hello packet (10 times max, every next pause will be longer and longer)
 
+	# args
+	local -r server_URL="$1"
+	local -r -n server_request_string="$2"
+	local -r -n server_response_string="$3"
+
 	# consts
 	local -r -i max_connection_attempts=10
 
 	# vars
 	local -i attempts_counter curl_exitcode
-	local timeout_options server_response
+	local timeout_options server_response jq_test_result
 
 	# code
+	print_JSON_with_header "Sending request to $server_URL" "$server_request_string"
+	echo
+
 	for (( attempts_counter = 1; attempts_counter <= max_connection_attempts; attempts_counter++ )); do
 		if (( attempts_counter == 1 )); then
 			# lower timeouts for the first connection attempt
@@ -438,24 +453,50 @@ function send_hello_packet {
 			# default timeouts
 			timeout_options=''
 		fi
-		server_response="$(
-			curl --insecure --location --data @- $timeout_options --silent \
-			--request POST "${HIVE_HOST_URL}/worker/api?id_rig=${RIG_ID-}&method=hello" \
-			--header "Content-Type: application/json" \
-			<<< "$request_json"
-		)"
+
+		# server sanity test first
+		server_response_string="$( curl --silent $timeout_options "$server_URL/worker/api?a=b" )"
 		curl_exitcode=$?
-		if (( curl_exitcode )); then
-			echo_error "$( human-curl-error $(( curl_exitcode )) )"
-			[[ -n "$server_response" ]] && echo_error "$server_response"
-			echo_error "Error connecting to $HIVE_HOST_URL (attempt #$attempts_counter), sleeping for ${attempts_counter}s..."
-			sleep $(( attempts_counter ))
+
+		if (( ! curl_exitcode )); then
+		#echo_error 'connected ok'
+			if [[ -n "$server_response_string" ]]; then
+				#echo_error 'response not empty ok'
+				if jq_test_result="$( jq 'if .error and .error.code then true else false end' <<< "$server_response_string" 2> /dev/null )"; then
+					#echo_error 'jq ok'
+					# this is the Hive API server
+					server_response_string="$(
+						curl --insecure --location --data @- --silent $timeout_options \
+						--request POST "$server_URL/worker/api?id_rig=${RIG_ID-}&method=hello" \
+						--header "Content-Type: application/json" \
+						<<< "$server_request_string"
+					)"
+					curl_exitcode=$?
+					break
+				else
+					echo_error "Not the Hive API response received from $server_URL. No second chances provided for this error."
+					curl_exitcode=1
+					break
+				fi
+			else
+				echo_error "Empty answer from $server_URL. No second chances provided for this error."
+				curl_exitcode=1
+				break
+			fi
 		else
-			break
+			echo_error "$( human-curl-error $(( curl_exitcode )) )"
+			[[ -n "$server_response_string" ]] && print_JSON_with_header 'Server response' "$server_response_string"
+			echo_error "Error connecting to $server_URL (attempt #$attempts_counter), sleeping for ${attempts_counter}s..."
+			sleep $(( attempts_counter ))
 		fi
 	done
 
-	echo "$server_response"
+	# show the server response
+	if [[ -n "$server_response_string" ]]; then
+		print_JSON_with_header 'Received response' "$server_response_json"
+		echo
+	fi
+
 	return $(( curl_exitcode ))
 }
 
@@ -603,22 +644,12 @@ if [[ -n "${FARM_HASH-}" ]]; then
 fi
 
 
-# show request json
-print_JSON_with_header 'Sending request' "$request_json"
-echo
-
-
 # send the hello packet
-server_response_json="$( send_hello_packet )" ||
-	die "Unable to connect to $HIVE_HOST_URL. No attempts left, exiting..." #404 is not a bad exit code
+send_hello_packet "$HIVE_HOST_URL" 'request_json' 'server_response_json' ||
+	die "Error connecting to $HIVE_HOST_URL. No attempts left, exiting..." #404 is not a bad exit code
 
 
-# show server response
-print_JSON_with_header 'Received response' "$server_response_json"
-echo
-
-
-# and then check json
+# and then check json received
 if server_error="$( jq --raw-output '.error' <<< "$server_response_json" )"; then
 	if is_JSON_string_not_empty_or_null "$server_error"; then
 		die "Server responded with error '$( jq --raw-output '.error.message' <<< "$server_response_json" )'" 1
