UPDATE ant-functions.sh, controller, hello
ant-functions.sh:
* renamed is_hiveon_fw_signed() to is_custom_fw_signed()

controller:
* renamed is_hiveon_fw_signed() to is_custom_fw_signed()

hello:
* neutralized H-vars
* improved serve_custom_fw_model_cache() to use ASIC_CUSTOM_FW_BRAND

diff --git a/hive/bin/hello b/hive/bin/hello
--- a/hive/bin/hello
+++ b/hive/bin/hello
@@ -12,7 +12,7 @@
 
 readonly script_mission='Client for ASICs: Say hello to the server'
 readonly script_mission_decription='Sends hello to server, receives config files, restarts miner'
-readonly script_version='0.3.2'
+readonly script_version='0.4.0'
 readonly script_basename="${0##*/}"
 #
 readonly script_DEBUG="${script_DEBUG:-0}" # use value from env if exists
@@ -382,10 +382,12 @@ function get_asic_json {
 	local asic_json
 
 	# code
-	[[ -s /usr/bin/compile_time && ! -s /usr/bin/compile_ver ]] &&
-		asic_json="$(		jq_raw_input_then_slurp /usr/bin/compile_time	'{"firmware": .[0], "model": .[1], "logic_version": .[2]}'						)"
-	[[ -s /usr/bin/compile_ver ]] &&
-		asic_json="$(		jq_raw_input_then_slurp /usr/bin/compile_ver	'{"firmware": .[0], "model": .[1], "logic_version": .[2]}'						)"
+	# shellcheck disable=SC2154
+	# bc defined in asic-model
+	[[ -s /usr/bin/compile_time && ! -s "$ASIC_CUSTOM_FW_description_file" ]] &&
+		asic_json="$(		jq_raw_input_then_slurp /usr/bin/compile_time				'{"firmware": .[0], "model": .[1], "logic_version": .[2]}'						)"
+	[[ -s "$ASIC_CUSTOM_FW_description_file" ]] &&
+		asic_json="$(		jq_raw_input_then_slurp "$ASIC_CUSTOM_FW_description_file"	'{"firmware": .[0], "model": .[1], "logic_version": .[2]}'						)"
 
 	case "$ASIC_MODEL" in
 		'Antminer D3 Blissz'*	)
@@ -533,7 +535,7 @@ function get_kernel_version {
 
 	# add signed status to a kernel info
 	if [[ "$ASIC_MODEL" == 'Antminer'* ]]; then
-		if ant-functions.sh is_hiveon_fw_signed; then
+		if ant-functions.sh is_custom_fw_signed; then
 			kernel_version+=' signed'
 		else
 			kernel_version+=' unsigned'
@@ -543,77 +545,77 @@ function get_kernel_version {
 	echo "$kernel_version"
 }
 
-function serve_hiveon_model_cache {
-	# Hiveon only: model cache
+function serve_custom_fw_model_cache {
+	# custom fw only: model cache
 
 	# consts
 	local -r antminer_compile_FILE='/usr/bin/compile_time'
-	local -r hiveon_compile_FILE='/usr/bin/compile_ver'
-	local -r hiveon_model_saved_FILE='/hive-config/model'
+	local -r custom_fw_model_saved_FILE='/hive-config/model'
 	local -r compile_ver_blacklist_RE='(TEST|Antminer X17|[Uu]nknown)'
 
 	# vars
-	local hiveon_model_detected='' hiveon_model_saved=''
+	local custom_fw_model_detected='' custom_fw_model_saved=''
 	local this_compile_file this_compile_file_2nd_line new_2nd_line
 
 	# code
-	echo_action 'Processing Hiveon model cache'
+	echo_action 'Processing custom fw model cache'
 	# try to get ASIC model from miner's log (Series 17)
-	if [[ -f "$hiveon_compile_FILE" && -s /var/log/log ]]; then
-		#hiveon_model_detected="$( grep -Fm1 -e 'Project type:' /var/log/log | awk -F': ' '{print $NF}' )" # old method
+	if [[ -f "$ASIC_CUSTOM_FW_description_file" && -s /var/log/log ]]; then
+		#custom_fw_model_detected="$( grep -Fm1 -e 'Project type:' /var/log/log | awk -F': ' '{print $NF}' )" # old method
 
 		# search for 2 patterns
 		# old one: 2020-10-02 04:48:01 driver/driver-btm-api.c:1450:bitmain_board_init: Project type: Antminer T17+
 		# new one: 2020-09-25 12:54:24 driver/driver-btm-api.c:2257:bitmain_soc_init: Miner compile time: Fri Sep 25 11:25:18 UTC 2020 type: Antminer S17 Hiveon
-		hiveon_model_detected="$( awk -F ' type: ' '/Project type: |Miner compile time:.+type: /{ print $NF; exit }' < /var/log/log )"
-		[[ -n "$hiveon_model_detected" ]] && echo_info "Model found in /var/log/log: '$hiveon_model_detected'"
+		# ^ new one is wrong! should test moar
+		custom_fw_model_detected="$( awk -F ' type: ' '/Project type: |Miner compile time:.+type: /{ print $NF; exit }' < /var/log/log )"
+		[[ -n "$custom_fw_model_detected" ]] && echo_info "Model found in /var/log/log: '$custom_fw_model_detected'"
 	fi
 
 	# remove saved model file if it contains 'TEST'
 	# shellcheck disable=SC2076
-	if [[ -s "$hiveon_compile_FILE" && "$( < "$hiveon_compile_FILE" )" =~ 'TEST' ]]; then
-		[[ -f "$hiveon_model_saved_FILE" ]] && rm "$hiveon_model_saved_FILE"
-		hiveon_model_detected=''
+	if [[ -s "$ASIC_CUSTOM_FW_description_file" && "$( < "$ASIC_CUSTOM_FW_description_file" )" =~ 'TEST' ]]; then
+		[[ -f "$custom_fw_model_saved_FILE" ]] && rm "$custom_fw_model_saved_FILE"
+		custom_fw_model_detected=''
 	fi
 
 	# remove saved model file if it contains blacklisted words
-	if [[ -s "$hiveon_model_saved_FILE" && "$( < "$hiveon_model_saved_FILE" )" =~ $compile_ver_blacklist_RE ]]; then
-		echo_warning "Model cache contains blacklisted words: '$( < "$hiveon_model_saved_FILE" )'. Cache cleared"
-		rm "$hiveon_model_saved_FILE"
+	if [[ -s "$custom_fw_model_saved_FILE" && "$( < "$custom_fw_model_saved_FILE" )" =~ $compile_ver_blacklist_RE ]]; then
+		echo_warning "Model cache contains blacklisted words: '$( < "$custom_fw_model_saved_FILE" )'. Cache cleared"
+		rm "$custom_fw_model_saved_FILE"
 	fi
 
-	if [[ -n "$hiveon_model_detected" ]]; then
-		if [[ "$hiveon_model_detected" =~ $compile_ver_blacklist_RE ]]; then
+	if [[ -n "$custom_fw_model_detected" ]]; then
+		if [[ "$custom_fw_model_detected" =~ $compile_ver_blacklist_RE ]]; then
 			# only warn user
-			echo_info "Detected model contains blacklisted words: '$hiveon_model_detected', skipped"
-			message warning "ASIC model detected: $hiveon_model_detected" --silent
-			hiveon_model_detected=''
+			echo_info "Detected model contains blacklisted words: '$custom_fw_model_detected', skipped"
+			message warning "ASIC model detected: $custom_fw_model_detected" --silent
+			custom_fw_model_detected=''
 		else
-			if [[ -s "$hiveon_model_saved_FILE" ]]; then
+			if [[ -s "$custom_fw_model_saved_FILE" ]]; then
 				# if model is saved -- get a saved model
-				hiveon_model_saved="$( < "$hiveon_model_saved_FILE" )"
-				echo_info "Got model from cache: '$hiveon_model_saved'"
+				custom_fw_model_saved="$( < "$custom_fw_model_saved_FILE" )"
+				echo_info "Got model from cache: '$custom_fw_model_saved'"
 			else
-				hiveon_model_saved=''
+				custom_fw_model_saved=''
 				echo_warning "Model cache empty or not found"
 			fi
-			if [[ "$hiveon_model_saved" != "$hiveon_model_detected" ]]; then
+			if [[ "$custom_fw_model_saved" != "$custom_fw_model_detected" ]]; then
 				# if detected model is different -- save detected model to file
-				message info "ASIC model re-detected: $hiveon_model_detected" --silent
-				echo_action "Saving detected model '$hiveon_model_detected' to the model cache"
-				echo "$hiveon_model_detected" > "$hiveon_model_saved_FILE"
+				message info "ASIC model re-detected: $custom_fw_model_detected" --silent
+				echo_action "Saving detected model '$custom_fw_model_detected' to the model cache"
+				echo "$custom_fw_model_detected" > "$custom_fw_model_saved_FILE"
 			fi
 		fi
 	fi
 
-	[[ -s "$hiveon_model_saved_FILE" ]] && hiveon_model_detected="$( < "$hiveon_model_saved_FILE" )"
+	[[ -s "$custom_fw_model_saved_FILE" ]] && custom_fw_model_detected="$( < "$custom_fw_model_saved_FILE" )"
 
-	if [[ -n "$hiveon_model_detected" && -s "$hiveon_compile_FILE" ]]; then
-		for this_compile_file in "$hiveon_compile_FILE" "$antminer_compile_FILE"; do
+	if [[ -n "$custom_fw_model_detected" && -s "$ASIC_CUSTOM_FW_description_file" ]]; then
+		for this_compile_file in "$ASIC_CUSTOM_FW_description_file" "$antminer_compile_FILE"; do
 			this_compile_file_2nd_line="$( sed -n '2p' "$this_compile_file" )"
-			if [[ "$this_compile_file_2nd_line" != "$hiveon_model_detected" ]]; then
-				# add 'Hiveon' to compile_* files
-				new_2nd_line="$hiveon_model_detected Hiveon"
+			if [[ "$this_compile_file_2nd_line" != "$custom_fw_model_detected" ]]; then
+				# add custom fw brand name to compile_* files
+				new_2nd_line="$custom_fw_model_detected $ASIC_CUSTOM_FW_BRAND"
 				echo_action "Processing $this_compile_file: '$this_compile_file_2nd_line' -> '$new_2nd_line'"
 				sed "2s|.*|$new_2nd_line|" -i "$this_compile_file"
 			fi
@@ -783,7 +785,7 @@ aes="$( grep -c '^Features.*aes' /proc/cpuinfo )"
 kernel="$( get_kernel_version )"
 hive_client_version="$( get_hive_client_version )"
 
-[[ -n "$HIVEON_VERSION" ]] && serve_hiveon_model_cache
+[[ -n "$ASIC_CUSTOM_FW_VERSION" ]] && serve_custom_fw_model_cache
 
 asic_json="$( get_asic_json )"
 uid="$( get_uid )"
@@ -887,7 +889,7 @@ if is_JSON_string_empty_or_null "$received_config"; then
 	die 'No "config" field in server response, exiting...' 1
 fi
 # shellcheck disable=SC2015
-echo "$received_config" > "$RIG_CONF" && echo_ok 'Received config saved' || echo_error 'Received config NOT saved'
+echo "$received_config" > "$RIG_CONF" && echo_ok 'Received config saved' || echo_error 'Received config NOT saved (write error)'
 # re-read rig.conf
 source "$RIG_CONF"
 #hostname-check
