UPDATE message
* tweaked connection timeouts
* added templates for tagging: %build%, %fw% and %profile%"
* improved UI

diff --git a/hive/bin/message b/hive/bin/message
--- a/hive/bin/message
+++ b/hive/bin/message
@@ -10,8 +10,8 @@
 #
 
 
-readonly script_mission='Client for ASICs: Messenger'
-readonly script_version='0.3.29'
+readonly script_mission='Client for ASICs: The Messenger'
+readonly script_version='0.4.0'
 readonly script_basename="$( basename "$0" )"
 #
 readonly script_DEBUG="${script_DEBUG:-1}" # use value from env if exists
@@ -24,9 +24,8 @@ set -o nounset
 
 # functions
 
-function errcho {
-	echo -e "${RED}${script_basename}>${NOCOLOR} $*"
-} 1>&2
+function errcho			{ echo -e "${RED-}${script_basename}>${NOCOLOR-} ${*}${NOCOLOR-}"; } 1>&2
+function echo_info		{ echo -e "${LGRAY-}${script_basename}>${NOCOLOR-} ${*}${NOCOLOR-}"; }
 
 function print_script_version {
 	echo -e "${YELLOW-}${script_mission}, version ${script_version}${NOCOLOR-}"
@@ -34,21 +33,42 @@ function print_script_version {
 }
 
 function print_script_usage {
-	echo -e "Usage: ${CYAN}$script_basename success|danger|warning|info \"message\" [OPTIONS]${NOCOLOR} - send a message to the dashboard"
-	echo -e "       ${CYAN}$script_basename file /path/filename  [OPTIONS]${NOCOLOR}                  - send a file to the dashboard"
-	echo -e "       ${CYAN}$script_basename file.io|transfer.sh /path/filename [OPTIONS]${NOCOLOR}    - send a file to the file sharing service"
-	echo -e "       ${CYAN}$script_basename tag 'your_tag' [OPTIONS]${NOCOLOR}                        - tag a worker with your_tag"
+	echo -e '  Usage:'
 	echo
-	echo -e 'Options:'
+	echo -e "    ${CYAN}$script_basename success|danger|warning|info \"message\" [OPTIONS]${NOCOLOR}    send a message to the dashboard"
+	echo -e "    ${CYAN}$script_basename ok|error|err|warn|default   \"message\" [OPTIONS]${NOCOLOR}    (alternative aliases)"
 	echo
-	echo -e "  ${CYAN}-i=msg_id${NOCOLOR}, ${CYAN}--id=msg_id${NOCOLOR} - add msg_id to a message (mostly used in 'agent' script)"
-	echo -e "  ${CYAN}--header=your_header${NOCOLOR}   - use a custom message header: 'message file /var/log/log --header=kernel.log'"
-	echo -e "  ${CYAN}--payload${NOCOLOR}              - add payload to a message (payload is read from stdin)"
-	echo -e "  ${CYAN}-s${NOCOLOR}, ${CYAN}--silent${NOCOLOR}           - silent mode, report only errors"
-	echo -e "  ${CYAN}-v${NOCOLOR}, ${CYAN}--verbose${NOCOLOR}          - verbose mode, show request & response"
+	echo -e "    ${CYAN}$script_basename file /path/filename [OPTIONS]${NOCOLOR}                      send a file to the dashboard"
+	echo -e "    ${CYAN}$script_basename file.io|transfer.sh /path/filename [OPTIONS]${NOCOLOR}       send a file to the file sharing service"
 	echo
-	echo 'Message type aliases: ok|error|err|warn|default'
+	echo -e "    ${CYAN}$script_basename tag \"your_tag\" [OPTIONS]${NOCOLOR}                           tag a worker, templates supported:"
+	echo -e "                                                               %build%, %fw% and %profile%"
 	echo
+	echo -e '  Options:'
+	echo
+	echo -e "    ${CYAN}-i=msg_id${NOCOLOR}, ${CYAN}--id=msg_id${NOCOLOR}    add msg_id to a message (mostly used in 'agent' script)"
+	echo -e "    ${CYAN}--header=your_header${NOCOLOR}      use a custom message header: 'message file /var/log/log --header=kernel.log'"
+	echo -e "    ${CYAN}--payload${NOCOLOR}                 add payload to a message (payload is read from stdin)"
+	echo -e "    ${CYAN}-s${NOCOLOR}, ${CYAN}--silent${NOCOLOR}              silent mode, report only errors"
+	echo -e "    ${CYAN}-v${NOCOLOR}, ${CYAN}--verbose${NOCOLOR}             verbose mode, show request & response"
+	echo
+}
+
+function print_all_matches {
+	#
+	# extract all RE matches from the string
+	# Usage: print_all_matches 'string' 'RE'
+	#
+
+	# args
+	local string_to_match="$1"
+	local -r RE="$2"
+
+	# code
+	while [[ "$string_to_match" =~ $RE ]]; do
+		string_to_match="${string_to_match//${BASH_REMATCH[0]}}"
+		echo "${BASH_REMATCH[0]}"
+	done
 }
 
 
@@ -108,6 +128,45 @@ case "$message_type" in
 
 	'tag')
 		message_color="$PURPLE"
+		tag_template_RE='%[[:alpha:]][[:alnum:]_]+%'
+		for this_template in $( print_all_matches "$message_header" "$tag_template_RE" ); do
+			this_template_substitution=''
+			case "${this_template,,}" in
+				'%fw%')
+					#
+					#/usr/bin/compile_ver:
+					#Tue Aug 18 09:03:07 UTC 2020
+					#Antminer T9 Hiveon
+					#1.03@200818
+					#
+					#/usr/bin/compile_time:
+					#Tue Aug 18 09:03:07 UTC 2020
+					#Antminer T9 Hiveon
+					#
+					if [[ -s /usr/bin/compile_ver ]]; then
+						this_template_substitution="$( sed -n '3p' /usr/bin/compile_ver )"
+					elif [[ -s /usr/bin/compile_time ]]; then
+						this_template_substitution="$( sed -n '1p' /usr/bin/compile_time )"
+					else
+						this_template_substitution='unknown fw'
+					fi
+				;;
+				'%build%')
+					if [[ -s /hive/etc/build ]]; then
+						this_template_substitution="$( < /hive/etc/build )"
+					else
+						this_template_substitution='unknown build'
+					fi
+				;;
+				'%profile%')
+					this_template_substitution="$( asic-oc status --active-profile-desc )" ||
+						this_template_substitution='unknown profile'
+				;;
+			esac
+			if [[ -n "$this_template_substitution" ]]; then
+				message_header="${message_header//$this_template/$this_template_substitution}"
+			fi
+		done
 	;;
 
 	'file')
@@ -180,10 +239,10 @@ if [[ -n "$file_to_send" ]]; then
 				else
 					file_io_success="$( jq --raw-output '.success' <<< "$filesharing_server_response" )"
 					if [[ "$file_io_success" == 'true' ]]; then
-						(( ! is_silent_FLAG )) && echo -e "${script_basename}> $console_message ${BGREEN}SENT${NOCOLOR}"
+						(( ! is_silent_FLAG )) && echo_info "$console_message ${BGREEN}SENT"
 						file_io_link="$( jq --raw-output '.link' <<< "$filesharing_server_response" )"
 						file_io_expiry="$( jq --raw-output '.expiry' <<< "$filesharing_server_response" )"
-						echo -e "${script_basename}> Download link ${WHITE}$file_io_link${NOCOLOR} will expire in $file_io_expiry"
+						echo_info "Download link ${WHITE}$file_io_link${NOCOLOR} will expire in $file_io_expiry"
 					else
 						errcho "$console_message ${BRED}SERVER ERROR${NOCOLOR}"
 						errcho "$file_send_method response: $filesharing_server_response${NOCOLOR}"
@@ -202,8 +261,8 @@ if [[ -n "$file_to_send" ]]; then
 					script_exitcode="$curl_exitcode"
 				else
 					if [[ "$filesharing_server_response" =~ ^https://transfer.sh/ ]]; then
-						(( ! is_silent_FLAG )) && echo -e "${script_basename}> $console_message ${BGREEN}SENT${NOCOLOR}"
-						echo -e "${script_basename}> Download link ${WHITE}$filesharing_server_response${NOCOLOR}"
+						(( ! is_silent_FLAG )) && echo_info "$console_message ${BGREEN}SENT"
+						echo_info "Download link ${WHITE}$filesharing_server_response"
 					else
 						errcho "$console_message ${BRED}SERVER ERROR${NOCOLOR}"
 						errcho "$file_send_method response: $filesharing_server_response${NOCOLOR}"
@@ -265,13 +324,14 @@ fi
 HIVE_API_endpoint="${HIVE_HOST_URL%/}/worker/api" # cut the trailing slash in HIVE_HOST_URL, if any (like as in rocketchain's local API server URL)
 
 # let's try to connect
-declare -r -i curl_initial_connect_timeout=5
-declare -r -i max_connection_attempts=10
+declare -r -i curl_initial_connect_timeout=0
+declare -r -i max_connection_attempts=15
 declare -i attempts_counter curl_connect_timeout curl_max_time
+declare attempts_message=''
 
 for (( attempts_counter = 1; attempts_counter <= max_connection_attempts; attempts_counter++ )); do
 	(( curl_connect_timeout = curl_initial_connect_timeout + attempts_counter ))
-	(( curl_max_time = curl_connect_timeout * 2 + 1 ))
+	(( curl_max_time = curl_connect_timeout * 3 ))
 	response="$(
 		curl \
 			--insecure --location --data @- --silent \
@@ -281,9 +341,11 @@ for (( attempts_counter = 1; attempts_counter <= max_connection_attempts; attemp
 		<<< "$request"
 	)"
 	curl_exitcode=$?
+	(( attempts_counter > 1 || curl_exitcode )) && attempts_message="[$attempts_counter/$max_connection_attempts] "
 	if (( curl_exitcode )); then
-		errcho "$console_message ${BRED}NETWORK ERROR${NOCOLOR} (attempt #$attempts_counter)"
-		errcho "$( human-curl-error "$curl_exitcode" )"
+		errcho "${attempts_message}$console_message ${BRED}FAIL ($curl_exitcode)${NOCOLOR}"
+		#errcho "$( human-curl-error "$curl_exitcode" )"
+		sleep "$attempts_counter"
 	else
 		break
 	fi
@@ -296,8 +358,8 @@ fi
 
 # check curl result
 if (( curl_exitcode )); then
-	errcho "$console_message ${BRED}NETWORK ERROR${NOCOLOR}"
-	errcho "$( human-curl-error "$curl_exitcode" )"
+	errcho "${attempts_message}$console_message ${BRED}FAIL ($curl_exitcode)${NOCOLOR}"
+	#errcho "$( human-curl-error "$curl_exitcode" )"
 	if (( ! is_verbose_FLAG )) && [[ -n "$response" ]]; then
 		errcho "Response: $response"
 	fi
@@ -307,7 +369,7 @@ else
 	error="$( jq '.error' --raw-output <<< "$response" )" # does the .error key is deprecated?
 	errors="$( jq 'if .errors.type != null then .errors.type[] else null end' --raw-output <<< "$response" )"
 	if [[ -n "$error" && "$error" != "null" ]] || [[ -n "$errors" && "$errors" != "null" ]]; then
-		errcho "$console_message ${BRED}API SERVER ERROR${NOCOLOR}"
+		errcho "${attempts_message}$console_message ${BRED}API SERVER ERROR${NOCOLOR}"
 		[[ -n "$error" && "$error" != "null" ]] && errcho "API server response: $error"
 		[[ -n "$errors" && "$errors" != "null" ]] && errcho "API server response: $errors"
 		if (( script_DEBUG )); then
@@ -316,7 +378,7 @@ else
 		fi
 		script_exitcode=1
 	else
-		(( ! is_silent_FLAG )) && echo -e "${script_basename}> $console_message ${BGREEN}SENT${NOCOLOR}"
+		(( ! is_silent_FLAG )) && echo_info "${attempts_message}$console_message ${BGREEN}SENT"
 	fi
 fi
 
