UPDATE message
* connected a hive-functions.sh library
* removed library functions
* added uniform RIG_CONF definition
* added template expansion in message_header field

diff --git a/hive/bin/message b/hive/bin/message
--- a/hive/bin/message
+++ b/hive/bin/message
@@ -11,10 +11,11 @@
 
 
 readonly script_mission='Client for ASICs: The Messenger'
-readonly script_version='0.4.2'
+readonly script_version='0.5.0'
 readonly script_basename="$( basename "$0" )"
 #
 readonly script_DEBUG="${script_DEBUG:-1}" # use value from env if exists
+source /hive/bin/hive-functions.sh || { echo 'ERROR: /hive/bin/hive-functions.sh not found'; exit 1; }
 
 
 # !!! bash strict mode, no unbound variables
@@ -27,49 +28,37 @@ set -o nounset
 function errcho			{ echo -e "${RED-}${script_basename}>${NOCOLOR-} ${*}${NOCOLOR-}"; } 1>&2
 function echo_info		{ echo -e "${LGRAY-}${script_basename}>${NOCOLOR-} ${*}${NOCOLOR-}"; }
 
-function print_script_version {
-	echo -e "${YELLOW-}${script_mission}, version ${script_version}${NOCOLOR-}"
-	echo
-}
-
 function print_script_usage {
 	echo -e '  Usage:'
 	echo
-	echo -e "    ${CYAN}$script_basename success|danger|warning|info \"message\" [OPTIONS]${NOCOLOR}    send a message to the dashboard"
-	echo -e "    ${CYAN}$script_basename ok|error|err|warn|default   \"message\" [OPTIONS]${NOCOLOR}    (alternative aliases)"
+	echo -e "    ${CYAN}$script_basename success|danger|warning|info \"text\" [OPTIONS]${NOCOLOR}    send a text message to the dashboard"
+	echo -e "    ${CYAN}$script_basename ok|error|err|warn|default   \"text\" [OPTIONS]${NOCOLOR}    (alternative aliases)"
 	echo
 	echo -e "    ${CYAN}$script_basename file /path/filename [OPTIONS]${NOCOLOR}                      send a file to the dashboard"
 	echo -e "    ${CYAN}$script_basename file.io|transfer.sh /path/filename [OPTIONS]${NOCOLOR}       send a file to the file sharing service"
 	echo
-	echo -e "    ${CYAN}$script_basename tag \"your_tag\" [OPTIONS]${NOCOLOR}                           tag a worker, templates supported:"
-	echo -e "                                                               %build%, %fw%, %profile% and %url%"
+	echo -e "    ${CYAN}$script_basename tag \"text\" [OPTIONS]${NOCOLOR}                           tag a worker with any text"
 	echo
 	echo -e '  Options:'
 	echo
-	echo -e "    ${CYAN}-i=msg_id${NOCOLOR}, ${CYAN}--id=msg_id${NOCOLOR}    add msg_id to a message (mostly used in 'agent' script)"
+	echo -e "    ${CYAN}-e${NOCOLOR}, ${CYAN}--escape-templates${NOCOLOR}    do not expand Hive templates (like %IP%) in a message header"
 	echo -e "    ${CYAN}--header=your_header${NOCOLOR}      use a custom message header: 'message file /var/log/log --header=kernel.log'"
+	echo -e "    ${CYAN}-i=msg_id${NOCOLOR}, ${CYAN}--id=msg_id${NOCOLOR}    add msg_id to a message (mostly used in 'agent' script)"
 	echo -e "    ${CYAN}--payload${NOCOLOR}                 add payload to a message (payload is read from stdin)"
 	echo -e "    ${CYAN}-s${NOCOLOR}, ${CYAN}--silent${NOCOLOR}              silent mode, report only errors"
 	echo -e "    ${CYAN}-v${NOCOLOR}, ${CYAN}--verbose${NOCOLOR}             verbose mode, show request & response"
 	echo
+	echo -e '  Supported templates in the text:'
+	echo
+	echo -e "    %BUILD%, %FW%, %HOSTNAME%, %IP%, %IP_SAFE%, %MAC%, %MAC_SAFE%, %PROFILE%, %URL%, %WORKER_NAME_RAW%"
+	echo
 }
 
-function print_all_matches {
-	#
-	# extract all RE matches from the string
-	# Usage: print_all_matches 'string' 'RE'
-	#
 
-	# args
-	local string_to_match="$1"
-	local -r RE="$2"
+# consts
 
-	# code
-	while [[ "$string_to_match" =~ $RE ]]; do
-		string_to_match="${string_to_match//${BASH_REMATCH[0]}}"
-		echo "${BASH_REMATCH[0]}"
-	done
-}
+declare -r RIG_CONF_default='/hive-config/rig.conf'
+declare -r RIG_CONF="${RIG_CONF:-$RIG_CONF_default}" # for ASIC emulator: set to default only if RIG_CONF variable is empty
 
 
 # vars
@@ -79,7 +68,8 @@ declare message_type message_header message_color
 declare id='' id_json payload='' payload_json
 declare request response
 declare file_to_send='' file_size
-declare -i curl_exitcode script_exitcode=0 is_silent_FLAG=0 is_verbose_FLAG=0
+declare -i curl_exitcode script_exitcode=0
+declare -i is_silent_FLAG=0 is_verbose_FLAG=0 is_templates_escaped_FLAG=0
 declare console_message=''
 
 
@@ -90,15 +80,12 @@ source colors
 
 # main
 
-# you could use externally defined RIG_CONF
-[[ -z "${RIG_CONF-}" ]] && RIG_CONF='/hive-config/rig.conf'
-
-if [[ ! -s "$RIG_CONF" ]]; then
+if [[ -s "$RIG_CONF" ]]; then
+	source "$RIG_CONF"
+else
 	errcho "Config file $RIG_CONF empty or not found"
 	exit 1
 fi
-
-source "$RIG_CONF"
 
 # process first two arguments
 message_type="${1-}"
@@ -128,51 +115,6 @@ case "$message_type" in
 
 	'tag')
 		message_color="$PURPLE"
-		tag_template_RE='%[[:alpha:]][[:alnum:]_]+%'
-		for this_template in $( print_all_matches "$message_header" "$tag_template_RE" ); do
-			this_template_substitution=''
-			case "${this_template,,}" in
-				'%fw%')
-					#
-					#/usr/bin/compile_ver:
-					#Tue Aug 18 09:03:07 UTC 2020
-					#Antminer T9 Hiveon
-					#1.03@200818
-					#
-					#/usr/bin/compile_time:
-					#Tue Aug 18 09:03:07 UTC 2020
-					#Antminer T9 Hiveon
-					#
-					if [[ -s /usr/bin/compile_ver ]]; then
-						this_template_substitution="$( sed -n '3p' /usr/bin/compile_ver )"
-					elif [[ -s /usr/bin/compile_time ]]; then
-						this_template_substitution="$( sed -n '1p' /usr/bin/compile_time )"
-					else
-						this_template_substitution='unknown fw'
-					fi
-				;;
-				'%build%')
-					if [[ -s /hive/etc/build ]]; then
-						this_template_substitution="$( < /hive/etc/build )"
-					else
-						this_template_substitution='unknown build'
-					fi
-				;;
-				'%profile%')
-					this_template_substitution="$( asic-oc status --active-profile-desc )" ||
-						this_template_substitution='unknown profile'
-				;;
-				'%url%')
-					#IFS='/' read -r _ _ this_template_substitution <<< "$HIVE_HOST_URL" # extract a domain name
-					#
-					# i think it should be an FQN
-					this_template_substitution="$HIVE_HOST_URL"
-				;;
-			esac
-			if [[ -n "$this_template_substitution" ]]; then
-				message_header="${message_header//$this_template/$this_template_substitution}"
-			fi
-		done
 	;;
 
 	'file')
@@ -196,6 +138,10 @@ esac
 # process arguments starting from 3rd
 for this_argument in "${@:3}"; do
 	case "$this_argument" in
+		'-e'|'--escape-templates')
+			is_templates_escaped_FLAG=1
+		;;
+
 		'-i='*|'--id='*)
 			id="${this_argument#*=}"
 		;;
@@ -222,6 +168,9 @@ for this_argument in "${@:3}"; do
 		;;
 	esac
 done
+
+# process templates
+[[ -n "$message_header" ]] && (( ! is_templates_escaped_FLAG )) && expand_hive_templates_in_variable_by_ref 'message_header'
 
 # send file
 if [[ -n "$file_to_send" ]]; then
