UPDATE miner
* mostly cosmetical: external sleep replaced with snore() built-in

diff --git a/hive/bin/miner b/hive/bin/miner
--- a/hive/bin/miner
+++ b/hive/bin/miner
@@ -9,9 +9,9 @@
 
 
 readonly script_mission='Client for ASICs: Miner controller'
-readonly script_version='1.1.2'
+readonly script_version='1.1.3'
 readonly script_basename="$( basename "$0" )"
-source /hive/bin/hive-functions.sh
+source /hive/bin/hive-functions.sh || { echo 'ERROR: /hive/bin/hive-functions.sh not found'; exit 1; }
 
 
 # functions
@@ -77,7 +77,7 @@ function miner_start {
 				fi
 				break
 			fi
-			sleep 1
+			snore 1
 		done
 	fi
 	echo
