Innosilicon A9 (pre)

diff --git a/hive/bin/selfupgrade b/hive/bin/selfupgrade
--- a/hive/bin/selfupgrade
+++ b/hive/bin/selfupgrade
@@ -72,8 +72,8 @@ install_a3_d3() {
 	if [ ! -d /config/hive ]; then
 		mkdir /config/hive
 	fi
-		tar -xzv -f $filename
-		cp -rf hiveos-asic-$release/* /config/hive/
+	tar -xzv -f $filename
+	cp -rf hiveos-asic-$release/* /config/hive/
 	[ $? -ne 0 ] && echo "Error extracting $filename" && exit 1
 
 	rm $filename
@@ -111,6 +111,57 @@ FILEEOF
 	bash -c "/hive/bin/firstrun $FARM_HASH"
 }
 
+install_innosilicon() {
+	echo ""
+	mount -o remount,rw,relatime,ubi=0,vol=0 -t ubifs ubi0:rootfs /
+	echo "> Extracting $filename"
+	if [ ! -d /config/hive ]; then
+		mkdir -p /config/hive/hive
+		mkdir /hive
+	fi
+	tar -xzv -f $filename
+	cp -rf hiveos-asic-$release/hive-config /config/hive/
+	cp -rf hiveos-asic-$release/hive/bin /config/hive/
+	cp -rf hiveos-asic-$release/hive/etc /config/hive/
+	cp -rf hiveos-asic-$release/hive/sbin /hive/
+	cp -rf hiveos-asic-$release/hive/lib /hive/
+	cp -rf hiveos-asic-$release/home/root/.profile /etc/profile.d/hive.sh
+	cp -rf hiveos-asic-$release/hive/share/innosilicon/* /etc/systemd/system/
+	[ $? -ne 0 ] && echo "Error extracting $filename" && exit 1
+
+	rm $filename
+
+	sleep 2
+
+	export PATH=$PATH:/hive/bin:/hive/sbin
+	export LD_LIBRARY_PATH=/hive/lib
+	
+	[ -L /hive/bin ] && [ -e /hive/bin ] && ln -s /config/hive/hive/bin/ /hive/bin
+	[ -L /hive/etc ] && [ -e /hive/etc ] && ln -s /config/hive/hive/etc/ /hive/etc
+	[ -L /hive-config ] && [ -e /hive-config ] && ln -s /config/hive/hive-config/ /hive-config
+	[ -L /hive-config ] && [ -e /hive-config ] && ln -s /config/hive/home/root/.profile /etc/profile.d/hive.sh
+	[ -L /hive/sbin/nc ] && [ -e /hive/sbin/nc ] && ln -s /hive/sbin/busybox.nosuid /hive/sbin/nc
+
+	#systemd autorun and cron
+	systemctl is-enabled hive.service > /dev/null
+	[[ $? == 1 ]] && systemctl enable hive.service
+	systemctl start hive.service
+	systemctl is-enabled hive-agent-screen.timer > /dev/null
+	[[ $? == 1 ]] && systemctl enable hive-agent-screen.timer
+	systemctl start hive-agent-screen.timer
+	systemctl is-enabled hive-cache-ip.timer > /dev/null
+	[[ $? == 1 ]] && systemctl enable hive-cache-ip.timer
+	systemctl start hive-cache-ip.timer
+
+	sleep 2
+
+	#$FARM_HASH can be defined externally
+	bash -c "/hive/bin/firstrun $FARM_HASH"
+}
+
+
+
+
 
 if [ "$ASIC_MODEL" == "Antminer S9" ]; then
 	echo "Install Antminer S9"
@@ -142,6 +193,9 @@ elif [ "$ASIC_MODEL" == "Antminer X3" ]; then
 elif [ "$ASIC_MODEL" == "Antminer T9+" ]; then
 	echo "Install Antminer T9+"
 	install_s9
+elif [ "$ASIC_MODEL" == "b29+.g19" ]; then
+	echo "Install Antminer A9"
+	install_innosilicon
 else
 	echo "Not found $ASIC_MODEL"
 	exit 1
