selfupgrade exicode

diff --git a/hive/bin/selfupgrade b/hive/bin/selfupgrade
--- a/hive/bin/selfupgrade
+++ b/hive/bin/selfupgrade
@@ -2,10 +2,11 @@
 
 ASIC_MODEL=`sed -n 2p /usr/bin/compile_time`
 release=`curl -f --silent -L --insecure https://raw.githubusercontent.com/minershive/hiveos-asic/master/hive/etc/VERSION`
+exitcode=$?
 filename=v$release.tar.gz
-if [[ $? -ne 0 || -z $release ]]; then
-	echo "Try again."
-	exit 1
+if [ $exitcode -ne 0 ] || [ -z $release ]; then
+	echo "Can't get current version from repository"
+	exit $exitcode
 fi
 if [ $# != "0" ]; then
 	release=$1
