UPDATE selfupgrade
* reverted to --url option
* refactored installation scheme
* invented do_install_for() preprocessor and moved a download/unpack tasks to it

diff --git a/hive/bin/selfupgrade b/hive/bin/selfupgrade
--- a/hive/bin/selfupgrade
+++ b/hive/bin/selfupgrade
@@ -11,7 +11,7 @@
 
 
 readonly script_mission='Client for ASICs: Update/install Client from repository'
-readonly script_version='0.16.0'
+readonly script_version='0.16.1'
 readonly script_basename="$( basename "$0" )"
 
 
@@ -168,10 +168,10 @@ print_script_usage () {
 	echo
 	echo '  Download source options:'
 	echo
-	echo -e "    ${WHITE}-g, --github${NOCOLOR}                           use Github as a repo"
-	echo -e "    ${WHITE}-m, --mirror${NOCOLOR}                           use our Github mirror as a repo"
-	echo -e "    ${WHITE}--mirror=http://yourserver.com/repo/${NOCOLOR}   use you own mirror as a repo, you have"
-	echo -e "                                           to copy ALL files from the default repo"
+	echo -e "    ${WHITE}-g, --github${NOCOLOR}                           update from Github repo"
+	echo -e "    ${WHITE}-m, --mirror${NOCOLOR}                           update from Github repo (mirror)"
+	echo -e "    ${WHITE}--url=http://yourserver.com/repo/${NOCOLOR}      update from a custom URL, you have to"
+	echo -e "                                           copy ALL files from the default repo"
 #	echo
 	echo '  Other options:'
 	echo
@@ -230,13 +230,13 @@ parse_arguments () {
 			'-m' | '--mirror')
 				download_from_github_mirror_repo_FLAG=1
 				;;
-			'--mirror='*)
-				custom_repo_URL="${this_ARG#*=}"
-				download_from_custom_repo_FLAG=1
-				;;
 			'--skip-build='*)
 				build_to_skip_ARG="${this_ARG#*=}"
 				[ "$local_build_version" = "$build_to_skip_ARG" ] && die "Local build is $local_build_version, skipped"
+				;;
+			'--url='*)
+				custom_repo_URL="${this_ARG#*=}"
+				download_from_custom_repo_FLAG=1
 				;;
 			'--help' | '-h' | *)
 				# here goes all other incorrect stuff
@@ -489,13 +489,11 @@ remove_needless_files () {
 
 	# args
 
-	if [ $# -eq 0 ]; then
-		return
-	fi
+	[ $# -eq 0 ] && return
 
 	# vars
 
-	local is_something_removed_FLAG=0
+	local is_something_happened_FLAG=0
 	local file_to_remove='' f='' message_body=''
 
 	# code
@@ -508,17 +506,17 @@ remove_needless_files () {
 				message_body="${message_body}${file_to_remove}"
 				# shellcheck disable=SC2086
 				if rm -rf $file_to_remove > /dev/null 2>&1; then
-					is_something_removed_FLAG=1
 					message_body="${message_body} "
 				else
 					message_body="${message_body} (FAIL) "
 				fi
+				is_something_happened_FLAG=1
 			fi
 			break
 		done
 	done
 
-	if [ "$is_something_removed_FLAG" -gt 0 ]; then
+	if [ "$is_something_happened_FLAG" -gt 0 ]; then
 		echo_action "Cleaning: $message_body"
 	fi
 }
@@ -585,6 +583,25 @@ wait_for_file () { # OBSOLETE, NOT USED ANYMORE
 # functions: model-specific install routines
 #
 
+do_install_for () {
+
+	# args
+
+	local install_type="$1"
+
+	# code
+
+	get_tar_gz_at_any_cost "$package_file_URL" "$package_file_to_download"
+	if [ "$install_type" != 'antminer_bmminer_ro' ]; then
+		untar_then_remove "$package_file_to_download"
+	else
+		untar_then_remove "$package_file_to_download" 'DO NOT REMOVE' # hehe we'll need it later
+	fi
+	remove_needless_files "hiveos-asic-${release_version_to_install}/hive/sbin/teleconsole" # remove the legacy teleconsole before copying
+
+	install_$install_type
+}
+
 execute_install_routine () {
 	echo -e -n "${GRAY}${script_basename}>${NOCOLOR} Installing Client for "
 
@@ -597,7 +614,7 @@ execute_install_routine () {
 		'Antminer DR3'			|\
 		'Antminer L3++'			|\
 		'Antminer S7'			|\
-		'Antminer X3')			echo "$ASIC_MODEL";				install_antminer_cgminer		;;
+		'Antminer X3')			echo "$ASIC_MODEL";				do_install_for 'antminer_cgminer'		;;
 
 		'Antminer E3'			|\
 		'Antminer S9 Hydro'		|\
@@ -606,63 +623,65 @@ execute_install_routine () {
 		'Antminer S9j'			|\
 		'Antminer S11'			|\
 		'Antminer T9'			|\
-		'Minecenter S9')		echo "$ASIC_MODEL";				install_antminer_bmminer		;;
+		'Minecenter S9')		echo "$ASIC_MODEL";				do_install_for 'antminer_bmminer'		;;
 
 		'Antminer S9 SE'		|\
 		'Antminer S9k'			|\
 		'Antminer S15'			|\
 		'Antminer T15'			|\
-		'Antminer X17')			echo "$ASIC_MODEL";				install_antminer_bmminer_ro		;;
+		'Antminer X17')			echo "$ASIC_MODEL";				do_install_for 'antminer_bmminer_ro'	;;
 
-		'Antminer Z9-Mini')		echo "$ASIC_MODEL";				install_antminer_Z9_cgminer		;;
+		'Antminer Z9-Mini')		echo "$ASIC_MODEL";				do_install_for 'antminer_Z9_cgminer'	;;
 
-		'Antminer ')			echo 'Antminer B3';				install_antminer_bmminer		;;
+		'Antminer ')			echo 'Antminer B3';				do_install_for 'antminer_bmminer'		;;
 
 		# Antminer, partial match
 
-		'Antminer D3 Blissz'*)	echo 'Antminer D3 Blissz';		install_antminer_cgminer		;;
-		'Antminer L3+'*)		echo 'Antminer L3+';			install_antminer_cgminer		;;
-		'Antminer S9 (vnish'*)	echo 'Antminer S9 vnish';		install_antminer_bmminer		;;
-		'Antminer S9'*)			echo 'Antminer S9';				install_antminer_bmminer		;;
-		'Antminer S10'*)		echo 'Antminer S10';			install_antminer_bmminer		;;
-		'Antminer S17'*)		echo 'Antminer S17';			install_antminer_bmminer_ro		;;
-		'Antminer T9+'*)		echo 'Antminer T9+';			install_antminer_bmminer		;;
-		'Antminer T9'*)			echo 'Antminer T9';				install_antminer_bmminer		;;
-		'Antminer T17'*)		echo 'Antminer T17';			install_antminer_bmminer_ro		;;
-		'Antminer Z9'*)			echo 'Antminer Z9';				install_antminer_Z9_cgminer		;;
-		'Antminer Z11'*)		echo 'Antminer Z11';			install_antminer_Z9_cgminer		;;
+		'Antminer D3 Blissz'*)	echo 'Antminer D3 Blissz';		do_install_for 'antminer_cgminer'		;;
+		'Antminer L3+'*)		echo 'Antminer L3+';			do_install_for 'antminer_cgminer'		;;
+		'Antminer S9 (vnish'*)	echo 'Antminer S9 vnish';		do_install_for 'antminer_bmminer'		;;
+		'Antminer S9'*)			echo 'Antminer S9';				do_install_for 'antminer_bmminer'		;;
+		'Antminer S10'*)		echo 'Antminer S10';			do_install_for 'antminer_bmminer'		;;
+		'Antminer S17'*)		echo 'Antminer S17';			do_install_for 'antminer_bmminer_ro'	;;
+		'Antminer T9+'*)		echo 'Antminer T9+';			do_install_for 'antminer_bmminer'		;;
+		'Antminer T9'*)			echo 'Antminer T9';				do_install_for 'antminer_bmminer'		;;
+		'Antminer T17'*)		echo 'Antminer T17';			do_install_for 'antminer_bmminer_ro'	;;
+		'Antminer Z9'*)			echo 'Antminer Z9';				do_install_for 'antminer_Z9_cgminer'	;;
+		'Antminer Z11'*)		echo 'Antminer Z11';			do_install_for 'antminer_Z9_cgminer'	;;
 
 		# Innosilicon
 
-		'b29+.g19')				echo 'Innosilicon A9';			install_innosilicon				;;
-		'd9.g19')				echo 'Innosilicon D9';			install_innosilicon				;;
-		's11.g19')				echo 'Innosilicon S11';			install_innosilicon				;;
-		't2th.soc')				echo 'Innosilicon T2Th';		install_innosilicon				;;
-		't2thf.soc')			echo 'Innosilicon T2Thf';		install_innosilicon				;;
-		't2thm.soc')			echo 'Innosilicon T2Thm';		install_innosilicon				;;
-		't2t.soc')				echo 'Innosilicon T2T-24T';		install_innosilicon				;;
-		't2t+.soc')				echo 'Innosilicon T2T+(32T)';	install_innosilicon				;;
-		't2th+.soc')			echo 'Innosilicon T2TH+';		install_innosilicon				;;
-		't2thf+.soc')			echo 'Innosilicon T2THf+';		install_innosilicon				;;
-		't2thl+.soc')			echo 'Innosilicon T2THl+';		install_innosilicon				;;
-		't2ti.soc')				echo 'Innosilicon T2Ti-25T';	install_innosilicon				;;
-		't2ts.soc')				echo 'Innosilicon T2Ts-26T';	install_innosilicon				;;
-		't2tz.soc')				echo 'Innosilicon T2Tz-30T';	install_innosilicon				;;
-		't3.soc')				echo 'Innosilicon T3';			install_innosilicon				;;
-		't3+.soc')				echo 'Innosilicon T3+';			install_innosilicon				;;
-		't3h+.soc')				echo 'Innosilicon T3H+';		install_innosilicon				;;
-		'T4.G19')				echo 'Innosilicon A8';			install_innosilicon_innominer	;;
+		'b29+.g19')				echo 'Innosilicon A9';			do_install_for 'innosilicon'			;;
+		'd9.g19')				echo 'Innosilicon D9';			do_install_for 'innosilicon'			;;
+		's11.g19')				echo 'Innosilicon S11';			do_install_for 'innosilicon'			;;
+		't2th.soc')				echo 'Innosilicon T2Th';		do_install_for 'innosilicon'			;;
+		't2thf.soc')			echo 'Innosilicon T2Thf';		do_install_for 'innosilicon'			;;
+		't2thm.soc')			echo 'Innosilicon T2Thm';		do_install_for 'innosilicon'			;;
+		't2t.soc')				echo 'Innosilicon T2T-24T';		do_install_for 'innosilicon'			;;
+		't2t+.soc')				echo 'Innosilicon T2T+(32T)';	do_install_for 'innosilicon'			;;
+		't2th+.soc')			echo 'Innosilicon T2TH+';		do_install_for 'innosilicon'			;;
+		't2thf+.soc')			echo 'Innosilicon T2THf+';		do_install_for 'innosilicon'			;;
+		't2thl+.soc')			echo 'Innosilicon T2THl+';		do_install_for 'innosilicon'			;;
+		't2ti.soc')				echo 'Innosilicon T2Ti-25T';	do_install_for 'innosilicon'			;;
+		't2ts.soc')				echo 'Innosilicon T2Ts-26T';	do_install_for 'innosilicon'			;;
+		't2tz.soc')				echo 'Innosilicon T2Tz-30T';	do_install_for 'innosilicon'			;;
+		't3.soc')				echo 'Innosilicon T3';			do_install_for 'innosilicon'			;;
+		't3+.soc')				echo 'Innosilicon T3+';			do_install_for 'innosilicon'			;;
+		't3h+.soc')				echo 'Innosilicon T3H+';		do_install_for 'innosilicon'			;;
+		'T4.G19')				echo 'Innosilicon A8';			do_install_for 'innosilicon_innominer'	;;
 
 		# Zig
 
 		'Zig Z1+'				|\
-		'Zig Z1')				echo "$ASIC_MODEL"; 			install_zig						;;
+		'Zig Z1')				echo "$ASIC_MODEL";				do_install_for 'zig'					;;
 
 		# Todek Toddminer C1 and C1 PRO eaglesong ASICs
-		'Toddminer C1'*)		echo "$ASIC_MODEL"; 			install_todd					;;
+
+		'Toddminer C1'*)		echo "$ASIC_MODEL";				do_install_for 'todd'					;;
 
 		# HashAltCoin FPGA Blackminer F1 series (multialgo)
-		'Blackminer F1'* )		echo "$ASIC_MODEL";			install_antminer_cgminer			;;
+
+		'Blackminer F1'*)		echo "$ASIC_MODEL";				do_install_for 'antminer_cgminer'		;;
 
 		# unknown
 
@@ -684,11 +703,6 @@ install_antminer_bmminer () {
 	#
 	# bmminer, / - rw, cron
 	#
-
-	get_tar_gz_at_any_cost "$package_file_URL" "$package_file_to_download"
-	untar_then_remove "$package_file_to_download"
-
-	remove_needless_files "hiveos-asic-${release_version_to_install}/hive/sbin/teleconsole" # remove the legacy teleconsole before copying
 
 	[ ! -d /config/hive/hive-config ] && mkdir -p /config/hive/hive-config
 	[ -L /hive ] && rm /hive
@@ -722,11 +736,6 @@ install_antminer_cgminer () {
 	#
 	# cgminer, / - ro, no cron
 	#
-
-	get_tar_gz_at_any_cost "$package_file_URL" "$package_file_to_download"
-	untar_then_remove "$package_file_to_download"
-
-	remove_needless_files "hiveos-asic-${release_version_to_install}/hive/sbin/teleconsole" # remove the legacy teleconsole before copying
 
 	[ ! -d /config/hive ] && mkdir /config/hive
 
@@ -770,11 +779,6 @@ install_antminer_Z9_cgminer () {
 	#
 	# cgminer, / - rw, no cron
 	#
-
-	get_tar_gz_at_any_cost "$package_file_URL" "$package_file_to_download"
-	untar_then_remove "$package_file_to_download"
-
-	remove_needless_files "hiveos-asic-${release_version_to_install}/hive/sbin/teleconsole" # remove the legacy teleconsole before copying
 
 	if [ -e /hive ] && [ ! -L /hive ]; then
 		mkdir -p /config/hive
@@ -828,11 +832,6 @@ install_innosilicon () {
 	#
 	#
 
-	get_tar_gz_at_any_cost "$package_file_URL" "$package_file_to_download"
-	untar_then_remove "$package_file_to_download"
-
-	remove_needless_files "hiveos-asic-${release_version_to_install}/hive/sbin/teleconsole" # remove the legacy teleconsole before copying
-
 	mount -o remount,rw,relatime,ubi=0,vol=0 -t ubifs ubi0:rootfs /
 	[ ! -d /config/hive ]	&& mkdir -p /config/hive
 	[ ! -d /hive ]			&& mkdir /hive
@@ -882,11 +881,6 @@ install_innosilicon_innominer () {
 	#
 	#
 	#
-
-	get_tar_gz_at_any_cost "$package_file_URL" "$package_file_to_download"
-	untar_then_remove "$package_file_to_download"
-
-	remove_needless_files "hiveos-asic-${release_version_to_install}/hive/sbin/teleconsole" # remove the legacy teleconsole before copying
 
 	mount -o remount,rw,relatime -t jffs2 /dev/root /
 	[ ! -d /hive ] && mkdir /hive
@@ -944,11 +938,6 @@ install_zig () {
 	#
 	#
 
-	get_tar_gz_at_any_cost "$package_file_URL" "$package_file_to_download"
-	untar_then_remove "$package_file_to_download"
-
-	remove_needless_files "hiveos-asic-${release_version_to_install}/hive/sbin/teleconsole" # remove the legacy teleconsole before copying
-
 	echo_action 'Copying to /'
 	cp -rf "hiveos-asic-${release_version_to_install}/"* / || die 'Copy error'
 
@@ -976,11 +965,6 @@ install_todd () {
 	#
 	#
 	#
-
-	get_tar_gz_at_any_cost "$package_file_URL" "$package_file_to_download"
-	untar_then_remove "$package_file_to_download"
-
-	remove_needless_files "hiveos-asic-${release_version_to_install}/hive/sbin/teleconsole" # remove the legacy teleconsole before copying
 
 	echo_action 'Copying to /'
 	cp -rf "hiveos-asic-${release_version_to_install}/"* / || die 'Copy error'
@@ -1014,21 +998,11 @@ install_antminer_bmminer_ro () {
 	local system_S69hive='/etc/rcS.d/S69hive'
 	local updated_S69hive='/hive/share/ant_15_17/S69hive'
 
-	# vars
-
-#	local persistent_package_filename_w_path="${NVRAM_path}/${persistent_package_filename}"
-
 	# code
 
+	echo_action 'Moving downloaded package to NVRAM'
+	mv -f "$package_file_to_download" "${NVRAM_path}/${persistent_package_filename}" || die 'Move error'
 	sync && echo 3 > /proc/sys/vm/drop_caches
-
-	# TODO why not to download and unpack it to /tmp as a common master.tar.gz -- and then mv it to $NVRAM_path/latest.tar.gz?
-	# so I can fully deduplicate downloading/untarring/deploying
-
-	cd "$NVRAM_path"
-
-	get_tar_gz_at_any_cost "$package_file_URL" "$persistent_package_filename"
-	untar_then_remove "$persistent_package_filename" 'DO NOT REMOVE'
 
 	remove_needless_files "${NVRAM_path}/latest_new.tar.gz" # delete a file from a legacy selfupgrade
 	remove_needless_files "hiveos-asic-${release_version_to_install}/hive/sbin/teleconsole" # remove the legacy teleconsole before copying
@@ -1044,8 +1018,7 @@ install_antminer_bmminer_ro () {
 	echo_action 'Copying finished, removing temporary files'
 	rm -rf hiveos-asic-* || echo_info 'Temporary files removing error'
 
-	# update system S69hive
-	# ??? do we still have to do this?
+	# update system S69hive, to ease the debugging that happens from time to time
 	if [ ! -f "$system_S69hive" ] || ! cmp -s "$system_S69hive" "$updated_S69hive"; then
 		cp -f "$updated_S69hive" "$system_S69hive"
 	fi
