UPDATE selfupgrade: quick check for correct version in arguments

diff --git a/hive/bin/selfupgrade b/hive/bin/selfupgrade
--- a/hive/bin/selfupgrade
+++ b/hive/bin/selfupgrade
@@ -383,13 +383,13 @@ install_antminer_bmminer_ro () {
 	[ -e /hive ] && rm -rf /hive
 	sync
 	if [ "$github" -eq 1 ]; then
-		curl -f -L --insecure http://github.com/minershive/hiveos-asic/archive/master.tar.gz -o /nvdata/latest.tar.gz
+		curl -f -L --insecure "$url" -o /nvdata/latest.tar.gz
 		/etc/rcS.d/S69hive
 	else
 		/etc/rcS.d/S69hive -f
 	fi
 	while [ ! -e /hive/sbin/ ]; do
-		echo "> Waiting for /hive/sbin/..."
+		echo "> selfupgrade waiting for /hive/sbin/..."
 		sleep 5
 	done
 	sleep 10
@@ -472,17 +472,28 @@ if [ $# -ne 0 ]; then
 		master=1
 		# check for master github or master devNNN
 		case "$2" in
-			github)				github=1;;
-			"${local_build_version}")	dont_have_to_update=1;;
+			github)
+				github=1
+			;;
+			"${local_build_version}")
+				dont_have_to_update=1
+			;;
 		esac
 	else
 		if [ "_${1}_" = '_-f_' ] || [ "_${1}_" = '_--force_' ]; then
 			force=1
 		else
-			user_defined_version="$1"
-			if [ "_${2}_" = '_-f_' ] || [ "_${2}_" = '_--force_' ]; then
-				force=1
-			fi
+			case "$1" in
+				*.*-*)
+					user_defined_version="$1"
+					if [ "_${2}_" = '_-f_' ] || [ "_${2}_" = '_--force_' ]; then
+						force=1
+					fi
+				;;
+				*)
+					dont_have_to_update=1
+				;;
+			esac
 		fi
 	fi
 fi
@@ -532,12 +543,12 @@ cd "$t"
 
 # some cleaning
 echo
-echo -n '> Cleaning '
+echo -n '> Cleaning: '
 for file_to_remove in /tmp/hive/* /tmp/hiveos-asic* /tmp/selfupgrade /tmp/master.tar.gz /tmp/v*.tar.gz "$filename" /hive/etc/build; do
 	if [ -e "$file_to_remove" ]; then
-		echo -n "$file_to_remove "
-		rm -rf "$file_to_remove" || echo -n '(FAIL), '
-		echo -n ', '
+		echo -n "$file_to_remove"
+		rm -rf "$file_to_remove" || echo -n ' (FAIL)'
+		echo -n ' '
 	fi
 done
 
@@ -621,6 +632,7 @@ case "$ASIC_MODEL" in
 
 	*)
 		echo "'$ASIC_MODEL'"
+		echo
 		echo 'ERROR: model not supported'
 		echo
 		echo 'Please contact us: https://t.me/hiveonasic_en'
