UPDATE selfupgrade: add nohup to delayed_agent_screen_restart

diff --git a/hive/bin/selfupgrade b/hive/bin/selfupgrade
--- a/hive/bin/selfupgrade
+++ b/hive/bin/selfupgrade
@@ -2,7 +2,7 @@
 
 
 readonly script_mission='Client for ASICs: Update/install Client from repository'
-readonly script_version='0.14.4'
+readonly script_version='0.14.5'
 readonly script_basename="$( basename "$0" )"
 
 
@@ -363,6 +363,11 @@ install_antminer_bmminer_ro () {
 	sync
 	if [ "$github_FLAG" -eq 1 ]; then
 		curl -L --insecure "$package_file_url" -o /nvdata/latest.tar.gz
+		# !!! have to talk with Pasha about this
+		#if [ $? -ne 0 ]; then
+		#	echo "Error downloading $package_file_url"
+		#	exit "$exitcode_NOT_OK"
+		#fi
 		/etc/rcS.d/S69hive
 	else
 		/etc/rcS.d/S69hive -f
@@ -869,7 +874,7 @@ parse_arguments "$@"
 set_package_url_and_file
 print_update_info
 set_temp_dir
-remove_needless_files "${temp_dir}/hive/*" "${temp_dir}/hiveos-asic*" "${temp_dir}/$script_basename" "${temp_dir}/master.tar.gz" "${temp_dir}/v*.tar.gz" "$package_file_to_download" /hive/etc/build
+remove_needless_files "${temp_dir}/hive/*" "${temp_dir}/hiveos-asic*" "${temp_dir}/$script_basename" "${temp_dir}/master.tar.gz" "${temp_dir}/v*.tar.gz" "$package_file_to_download" /hive/etc/build # bug: we delete build file upfront but a downloading or an extracting process can be aborted
 execute_install_routine
 
 #Don't restart it...
@@ -877,7 +882,7 @@ execute_install_routine
 #hello restartminer
 
 remove_needless_files "${temp_dir}/hiveos-asic*"
-delayed_agent_screen_restart & # buys a little time for previous agent to send the OK message
+nohup delayed_agent_screen_restart > /dev/null 2>&1 & # buys a little time for previous agent to send the OK message
 echo
 echo -e "${GREEN}Update complete. Have a happy mining.${NOCOLOR}"
 sync
