UPDATE wd
* refactored load_configuration() to load only if the config is changed
* removed jq call -- added pure bash get_max_of_three_numbers()
* increased sleep_time up to 20 seconds

diff --git a/hive/bin/wd b/hive/bin/wd
--- a/hive/bin/wd
+++ b/hive/bin/wd
@@ -9,56 +9,89 @@
 
 
 readonly script_mission='Client for ASICs: Hashrate Watchdog'
-readonly script_version='0.2.9'
+readonly script_version='0.3.0'
 readonly script_basename="$( basename "$0" )"
 
 
 # functions
 
 function load_configuration {
-	if [[ -f "$RIG_CONF" ]]; then
-		source "$RIG_CONF"
+	# vars
+	local -i current_RIG_CONF_date
+
+	# code
+	if [[ -s "$RIG_CONF" ]]; then
+		current_RIG_CONF_date="$( get_file_last_modified_time_in_seconds "$RIG_CONF" )"
+		if (( last_RIG_CONF_date != current_RIG_CONF_date )); then
+			if (( last_RIG_CONF_date == 0 )); then
+				log_line info "Loading & processing $RIG_CONF..."
+			else
+				log_line info "$RIG_CONF have changed since last check. Reloading & processing..."
+			fi
+
+			(( last_RIG_CONF_date = current_RIG_CONF_date )) # update a date
+			source "$RIG_CONF"
+
+			# set to 0 if empty or not defined
+			: "${WD_ENABLED:=0}"
+			: "${WD_REBOOT:=0}"
+			: "${WD_MINER:=0}"
+
+			if (( ! WD_ENABLED )); then
+				log_line warning 'Watchdog not enabled, exiting'
+				exit 0
+			fi
+
+			if (( ( ! WD_MINER ) && ( ! WD_REBOOT ) )); then
+				message warning 'Restart and reboot timers both set to 0 (zero) minutes. Hahsrate Watchdog disabled. Please configure properly' --silent
+				log_line warning 'Restart and reboot timers both set to 0 (zero) minutes. Watchdog not enabled, exiting'
+				exit 1
+			fi
+
+			minhash="$( jq --raw-output ".\"$MINER\"" <<< "$WD_MINHASHES" )"
+			if is_JSON_string_empty_or_null "$minhash"; then
+				message warning "Minimal hashrate for $MINER is not set. You have to configure Hashrate Watchdog" --silent
+				log_line error "Minimal hashrate for $MINER is not set in config, exiting"
+				exit 1
+			fi
+			log_line info "Miner restart in ${WHITE}$WD_MINER${NOCOLOR}m and worker reboot in ${WHITE}$WD_REBOOT${NOCOLOR}m if hashrate < ${WHITE}$( khs_to_human_friendly_hashrate "$minhash" )${NOCOLOR}"
+		else
+			(( script_DEBUG )) && log_line debug "Config file $RIG_CONF have not changed since last check. Skipping..."
+		fi
 	else
-		log_line error "Config file $RIG_CONF not found, exiting"
-		exit 1
-	fi
-
-	# set to 0 if empty or not defined
-	: "${WD_ENABLED:=0}"
-	: "${WD_REBOOT:=0}"
-	: "${WD_MINER:=0}"
-
-	if (( ! WD_ENABLED )); then
-		log_line warning 'Watchdog not enabled, exiting'
-		exit 0
-	fi
-
-	if (( ( ! WD_MINER ) && ( ! WD_REBOOT ) )); then
-		message warning 'Restart and reboot timers both set to 0 (zero) minutes. Hahsrate Watchdog disabled. Please configure properly' --silent
-		log_line warning 'Restart and reboot timers both set to 0 (zero) minutes. Watchdog not enabled, exiting'
-		exit 1
-	fi
-
-	minhash="$( jq --raw-output ".\"$MINER\"" <<< "$WD_MINHASHES" )"
-	if is_JSON_string_empty_or_null "$minhash"; then
-		message warning "Minimal hashrate for $MINER is not set. You have to configure Hashrate Watchdog" --silent
-		log_line error "Minimal hashrate for $MINER is not set in config, exiting"
+		log_line error "Config file $RIG_CONF not found or empty, exiting"
 		exit 1
 	fi
 }
 
 function set_lastgood {
-	if [[ -f "$khs_file" ]]; then
-#		lastgood=`stat -c %Y "$khs_file"`
-#		lastgood="$( date -r "$khs_file" +%s )"
-		lastgood="$( get_file_last_modified_time_in_seconds "$khs_file" )"
+	if [[ -f "$khs_FILE" ]]; then
+		#lastgood_khs=`stat -c %Y "$khs_FILE"`
+		#lastgood_khs="$( date -r "$khs_FILE" +%s )"
+		lastgood_khs="$( get_file_last_modified_time_in_seconds "$khs_FILE" )"
 	else
-		#lastgood=0 can't set it to 0, in case of boot agent may be late
-		printf -v lastgood '%(%s)T' -1 #let's count from now
-#		lastgood="$( date +%s )"
+		#lastgood_khs=0 can't set it to 0, in case of boot agent may be late
+		#lastgood_khs="$( date +%s )"
+		lastgood_khs="$( get_current_system_time_in_seconds )" # let's count from now on
 	fi
 
 	miner_restart_count=0
+}
+
+function get_max_of_three_numbers {
+	# args
+	local -r -i num1="$1"
+	local -r -i num2="$2"
+	local -r -i num3="$3"
+
+	# code
+	if (( num1 > num2 && num1 > num3 )); then
+		echo "$num1"
+	elif (( num2 > num1 && num2 > num3 )); then
+		echo "$num2"
+	else
+		echo "$num3"
+	fi
 }
 
 function loop {
@@ -67,11 +100,12 @@ function loop {
 
 	# vars
 	local -i khs_decimal minhash_decimal elapsed_safe_limit
+	local khs
 
 	# code
 	load_configuration
 
-	[[ -f "$khs_file" ]] && khs="$( < "$khs_file" )"
+	[[ -s "$khs_FILE" ]] && khs="$( < "$khs_FILE" )"
 	: "${khs:=0}" # set to 0 if empty or not defined
 
 	khs_decimal="$( scientific_to_decimal "$khs" )"
@@ -80,16 +114,16 @@ function loop {
 	if (( khs_decimal >= minhash_decimal )); then
 		set_lastgood
 		if (( ok_count == 0 )); then
-			log_line ok "$MINER hashrate ${WHITE}$( khs_to_human_friendly_hashrate "$khs" )${NOCOLOR} ${GREEN}>=${NOCOLOR} ${WHITE}$( khs_to_human_friendly_hashrate "$minhash" )${NOCOLOR}"
+			log_line ok "$MINER hashrate OK (${WHITE}$( khs_to_human_friendly_hashrate "$khs" )${NOCOLOR} ${GREEN}>=${NOCOLOR} ${WHITE}$( khs_to_human_friendly_hashrate "$minhash" )${NOCOLOR})"
 		fi
 		(( ok_count++ ))
 		(( ok_count >= OK_MESSAGE_REDUCE )) && ok_count=0
 		return
 	fi
 
-	printf -v now '%(%s)T' -1
-	(( elapsed = now - lastgood ))
-	elapsed_safe_limit="$( jq --slurp 'max' <<< "$(( WD_REBOOT * 60 )) $(( WD_MINER * 60 )) $(( seconds_in_24h ))" )" #"# get max of these numbers
+	now="$( get_current_system_time_in_seconds )"
+	(( elapsed = now - lastgood_khs ))
+	elapsed_safe_limit="$( get_max_of_three_numbers $(( WD_REBOOT * 60 )) $(( WD_MINER * 60 )) $(( seconds_in_24h )) )"
 
 	if (( elapsed > elapsed_safe_limit || elapsed < 0 )); then
 		# most likely the system date was changed
@@ -97,7 +131,7 @@ function loop {
 		log_line warning '!'
 		log_line warning '! GRR-GRR! Something wrong with the system time?'
 		log_line warning "! The last valid result was received a ${WHITE}$( seconds2dhms "$elapsed" )${NOCOLOR} ago"
-		log_line warning '! Watchdog resetted to a current time'
+		log_line warning '! Watchdog reset to a current time'
 		log_line warning '!'
 		# let's give another chance: update lastgood to a current datetime
 		set_lastgood
@@ -118,7 +152,7 @@ function loop {
 	if (( WD_REBOOT )); then
 		(( reboot_timeout = WD_REBOOT * 60 ))
 		if (( elapsed >= reboot_timeout )); then
-			message danger "$MINER low hashrate ($( khs_to_human_friendly_hashrate "$khs" )), rebooting" --silent
+			message danger "Hashrate Watchdog: low hashrate ($( khs_to_human_friendly_hashrate "$khs" )) for $( seconds2dhms "$elapsed" ), rebooting" --silent
 			log_line error '!'
 			log_line error "! Rebooting after $WD_REBOOT minutes of continuous barking"
 			log_line error '!'
@@ -132,7 +166,7 @@ function loop {
 	if (( WD_MINER )); then
 		(( miner_restart_timeout = WD_MINER * 60 ))
 		if (( miner_restart_count == 0 && elapsed >= miner_restart_timeout )); then
-			message warning "$MINER low hashrate ($( khs_to_human_friendly_hashrate "$khs" )), restarting" --silent
+			message warning "Hashrate Watchdog: low hashrate ($( khs_to_human_friendly_hashrate "$khs" )) for $( seconds2dhms "$elapsed" ), restarting" --silent
 			log_line warning '!'
 			log_line warning "! Restarting $MINER after $WD_MINER minutes of continuous barking"
 			log_line warning '!'
@@ -145,14 +179,17 @@ function loop {
 
 # consts
 
-declare -r sleep_time=10 # seconds to sleep over iteration
+declare -r sleep_time=20 # seconds to sleep over iteration
 declare -r OK_MESSAGE_REDUCE=$(( 1 * 60 / sleep_time )) # e.g. only every 12th message will be displayed to reduce log
 declare -r RIG_CONF='/hive-config/rig.conf'
-declare -r khs_file='/run/hive/khs'
+declare -r khs_FILE='/run/hive/khs'
+declare -r arr_FILE='/run/hive/arr' # accepted/rejected ratio file, reserved for future development
+
 
 # vars
 
-declare -i ok_count=0 miner_restart_count lastgood
+declare -i ok_count=0 miner_restart_count lastgood_khs lastgood_arr last_RIG_CONF_date
+declare minhash
 
 
 # sources
@@ -167,10 +204,9 @@ set_lastgood
 
 case "$1" in
 	'run'|'start')
-		load_configuration
-
 		log_line ok "$script_mission, version $script_version started"
-		log_line info "Miner restart in ${WHITE}$WD_MINER${NOCOLOR}m and worker reboot in ${WHITE}$WD_REBOOT${NOCOLOR}m if hashrate < ${WHITE}$( khs_to_human_friendly_hashrate "$minhash" )${NOCOLOR}"
+
+		load_configuration
 
 		while true; do
 			loop
@@ -179,6 +215,7 @@ case "$1" in
 	;;
 
 	'stop')
+		# TODO get rid of 'stop' made out of shit and sticks -- refactor to stop on SIGUSR1 or SIGSTOP
 		printf -v marker '%(%s)T-%s-%u%u' -1 "$FUNCNAME" "${RANDOM}" "${RANDOM}"
 		self="(${$}|${BASHPID})[[:space:]].+$0"
 		if ps w | grep -F -e "$0" -e "$marker" | grep -Ev -e "$marker" -e "$self" | awk '{print $1}' | xargs kill > /dev/null 2>&1; then
